Step 2 – reading web3 near certified developer level 1
near-x/learn-near-community pull request #10
Opened 2021-07-03 05:54 UTC by shepf

2021-07-06 11:44 UTC, tigerjibo reviewed
review

2021-07-06 11:44 UTC, tigerjibo commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +学习阅读控制资金，身份和所有权的合约。adfa
```suggestion
学习阅读关于控制资金，身份和所有权的合约
```

2021-07-10 17:49 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +
可以考慮多次快速閱讀而不是一次性的慢慢閱讀。閱讀[How to survey?](https://hackmd.io/@nearly-learning/how-to-survey) 可以讓你明白為什麼和怎樣去做。

2021-07-10 17:52 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +* Rust合约 始终位于名为lib.rs的文件中。
```suggestion
* Rust合约 位于名为lib.rs的文件中。
```

2021-07-14 04:34 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +
補充一下，
原文有一段
"Consider that it is better to read many times quickly and NOT just one time slowly. Read How to survey? to better understand why and how you can do this"

2021-07-14 04:44 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +* 查看您的语言标记为“CORE Activity”的3份合约
```suggestion
* 查看您所选的语言中标记为“CORE Activity”的3份合约
```

2021-07-14 04:48 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +clone所选语言的 starter 库并按照说明进行操作
```suggestion
複製(clone)你所选语言的 starter 库并按照说明进行操作
```

2021-07-14 04:50 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +您阅读得越多越好，如果可以的话，继续阅读下去。记住要把注意力集中在阅读上，避免一些有关构建和运行上的问题的诱惑，因为这会分散您的注意力。明天您好就可以构建和运行。
```suggestion
您阅读得越多越好，如果可以的话，继续阅读下去。记住要把注意力集中在阅读上，避免一些有关构建和运行上的问题的诱惑，因为这会分散您的注意力。明天，您就可以构建和运行所有东西。
```

2021-07-14 04:55 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +3. 查看这些小难题，它们可能对您很有趣
```suggestion
3. 查看这些小难题，您可能会在它们中获得乐趣
```

2021-07-14 04:58 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +* 审计[Illia的合约仓库](https://github.com/ilblackdragon/contracts)
```suggestion
*  查看[Illia的合约仓库](https://github.com/ilblackdragon/contracts)
```

2021-07-14 04:58 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +* 审计所有的彩虹桥黑客马拉松合约
```suggestion
* 查看所有的彩虹桥黑客马拉松合约
```

2021-07-14 05:03 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +* 查看所有[核心合约](https://github.com/near/core-contracts) 和观看在线代码审计[视频](https://www.youtube.com/watch?v=BA7VeUS_RAA&list=PL9tzQn_TEuFXnYksuNJwrl1l_AuWzn6eF)
```suggestion
* 查看所有[核心合约](https://github.com/near/core-contracts) 和观看相关的在线代码评论[视频](https://www.youtube.com/watch?v=BA7VeUS_RAA&list=PL9tzQn_TEuFXnYksuNJwrl1l_AuWzn6eF)
```

2021-07-14 05:03 UTC, shepf commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +clone所选语言的 starter 库并按照说明进行操作
专业术语，这个不用改了吧

2021-07-14 05:07 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +1. 阅读您所选择的语言的所有合约，而不仅仅是3种
```suggestion
1. 阅读您所选择的语言的所有合约，而不仅仅是3份
```

2021-07-14 05:08 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +您应该至少阅读**3个**标记为**CORE Activity**的合约。
```suggestion
您应该至少阅读**3份**标记为**CORE Activity**的合约。
```

2021-07-14 05:08 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +您应该至少阅读**3个**标记为**CORE Activity**的合约。
```suggestion
您应该至少阅读**3份**标记为**CORE Activity**的合约。
```

2021-07-14 05:09 UTC, shepf commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +clone所选语言的 starter 库并按照说明进行操作
```suggestion
复制（clone）所选语言的 starter 库并按照说明进行操作
```

2021-07-14 05:15 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +您可以阅读有关[Rust合约](https://hackmd.io/@nearly-learning/contract-basics-rust)基础的更多信息，也可以观看[视频](https://www.youtube.com/watch?v=AOvqsD-rBUw)。
```suggestion
您可以阅读更多有关[Rust合约的基础知识](https://hackmd.io/@nearly-learning/contract-basics-rust)，也可以选择观看[视频](https://www.youtube.com/watch?v=AOvqsD-rBUw)以了解Rust合约。
```

2021-07-14 05:27 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +* 理解这个合约哪一部分对您来说是挑战
```suggestion
* 在阅读这个合约过程中，哪一部分对您来说是最具挑战
```

2021-07-14 05:28 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +* 理解这个合约哪一部分对您来说是挑战
```suggestion
* 在阅读这个合约过程中，哪一部分对您来说是最具挑战
```

2021-07-29 04:47 UTC, think-in-universe requested changes
翻译时，注意格式与原文匹配

2021-07-29 04:47 UTC, think-in-universe commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +* Rust合约 位于名为lib.rs的文件中。
```suggestion
* Rust合约 位于名为`lib.rs`的文件中。
```

2021-07-29 04:47 UTC, think-in-universe commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +* Rust合约 位于名为lib.rs的文件中。
文件名可以采用 \`filename\`  语法标记，下同

2021-07-29 04:47 UTC, think-in-universe commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +核心活动：
1. heading 应添加格式
2. 丢失了 emoji

2021-07-29 04:47 UTC, think-in-universe commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +核心活动：
下同

2021-08-08 01:48 UTC, shepf commented
fixed

2021-08-12 06:23 UTC, danielwpz requested changes

2021-08-12 06:23 UTC, danielwpz commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +有时人们不确定如何完成此活动。 如下技巧可能会有所帮助。
```suggestion
一开始可能会不知所措，如下技巧可能会帮助到你：
```

2021-08-12 06:23 UTC, danielwpz commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +复制（clone）所选语言的 starter 库并按照说明进行操作
```suggestion
克隆（clone）所选语言的 starter 库并按照说明进行操作
```

2021-08-12 06:23 UTC, danielwpz commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +您阅读得越多越好，如果可以的话，继续阅读下去。记住要把注意力集中在阅读上，避免一些有关构建和运行上的问题的诱惑，因为这会分散您的注意力。明天，您就可以构建和运行所有东西。
```suggestion
您阅读得越多越好，如果可以的话，继续阅读下去。记住要把注意力集中在阅读上，先不去考虑有关构建和运行上的问题，因为这会分散您的注意力。明天，您就可以构建和运行所有东西。
```

2021-08-12 06:23 UTC, danielwpz commented on cn/resources/ncd/level1/step-2-reading-web3-near-certified-developer-level-1.md
> +3. 查看这些小难题，您可能会在它们中获得乐趣
```suggestion
3. 看看下面这些小的挑战，您可能会在它们中获得乐趣
```

2021-08-12 19:17 UTC, think-in-universe commented
The PR is not ready actually, but I have to merge it first, and then fix the remaining issues.

2021-08-12 19:17 UTC, merged

2021-08-18 14:36 UTC, MartinYeung5 commented
翻译质量评价: 一般

2021-09-03 06:17 UTC, think-in-universe commented
翻译质量评价：一般