Step 3 – writing web3 near certified developer level 1
near-x/learn-near-community pull request #11
Opened 2021-07-03 07:58 UTC by shepf

2021-07-22 07:55 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +学习编写控制资金，身份和所有权的合约。
```suggestion
学习编写在合约中对资金，身份和所有权的控制。
```

2021-07-29 04:52 UTC, think-in-universe requested changes

2021-07-29 04:52 UTC, think-in-universe commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +>To call methods, and methods, and methods, signing transactions in this petty pace from day to day, to the last token of recorded block height;
未翻译，请翻译完成后再次提交审阅

2021-07-29 06:52 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +确保clone 每个repository 并在本地构建。 使每个应用程序运行与阅读代码一样重要，因为今天您将专注于理解所有组件的工作方式。
```suggestion
确保複制每个仓库(repository)并在本地构建。 使每个应用程序运行与阅读代码一样重要，因为今天您将专注于理解所有组件的工作方式。
```

2021-07-29 07:00 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +* 审查您所选语言标记为“CORE Activity”的3个应用程序
```suggestion
* 複习您所选语言标记为“CORE Activity”的3个应用程序
```

2021-07-29 07:09 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +4. 以某种方式测试合约，以便您知道它是否有效。 您可以使用NEAR CLI命令或运行现有的单元测试或模拟测试，或者如果dApp有一个，则甚至可以使用Web界面来执行此操作。
选择一个您认为可行的方式来测试合约。 您可以使用NEAR CLI命令或运行现有的单元测试或模拟测试。如果有dApp的话，甚至可以使用网页界面来执行此操作。

2021-07-29 07:11 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +4. 以某种方式测试合约，以便您知道它是否有效。 您可以使用NEAR CLI命令或运行现有的单元测试或模拟测试，或者如果dApp有一个，则甚至可以使用Web界面来执行此操作。
在這裡還有一句沒翻譯:
"The KEY idea here is to make sure you will NOTICE a change to the contract if you make one"

2021-07-29 07:14 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +7. 您所做的更改是否按预期进行了？ 还是你弄坏了什么？
```suggestion
7. 您所做的更改是否按预期进行了？ 还是有什么出错？
```

2021-07-29 07:14 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +8. 需要帮助时寻求帮助
```suggestion
8. 需要帮助时，可寻求帮助
```

2021-07-29 07:18 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +您看到的应用程序越多，您将对NEAR可能产生的想法有了更多的了解。
```suggestion
您看到的应用程序越多，您将对NEAR能做到的事有更多的了解。
```

2021-07-29 07:26 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +    - #2. [debugging challenge](https://github.com/Learn-NEAR/workshop--exploring-assemblyscript-contracts#activitydebugging-challenge) to fix a few failing unit tests with broken contracts
這裡有一句還沒完成翻譯

2021-07-29 10:59 UTC, shepf commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +* 审查您所选语言标记为“CORE Activity”的3个应用程序
审查比较好吧

2021-07-31 08:39 UTC, tigerjibo commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +>To call methods, and methods, and methods, signing transactions in this petty pace from day to day, to the last token of recorded block height;
```suggestion
>To call methods, and methods, and methods, signing transactions in this petty pace from day to day, to the last token of recorded block height;
```
```suggestion
>调用方法、方法和方法，每天以这种琐碎的速度签署事务，直到记录的块高度的最后一个标记;
```

2021-08-08 01:49 UTC, shepf commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +确保clone 每个repository 并在本地构建。 使每个应用程序运行与阅读代码一样重要，因为今天您将专注于理解所有组件的工作方式。
```suggestion
确保复制（clone）每个仓库(repository)并在本地构建。 使每个应用程序运行与阅读代码一样重要，因为今天您将专注于理解所有组件的工作方式
```

2021-08-12 08:02 UTC, danielwpz reviewed
时间关系我直接修改了哈，如果还有问题可以再提交一个新的pr

2021-08-12 08:02 UTC, danielwpz commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +### 非合约
```suggestion
### 无合约
```

2021-08-12 08:02 UTC, danielwpz commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +以下是这些示例：[ OPEN the list of apps using NO CONTRACT ](https://airtable.com/shr5VqiNCEoPWl0JQ/tblm1quryzSbqBzCK)
```suggestion
以下是这些示例：[无合约示例](https://airtable.com/shr5VqiNCEoPWl0JQ/tblm1quryzSbqBzCK)
```

2021-08-12 08:02 UTC, danielwpz commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +## NCDL1 写 web3 任务
```suggestion
## NCDL1 本章作业
```

2021-08-12 08:05 UTC, danielwpz commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +4. 以某种方式测试合约，以便您知道它是否有效。 您可以使用NEAR CLI命令或运行现有的单元测试或模拟测试，或者如果dApp有一个，则甚至可以使用Web界面来执行此操作。
```suggestion
4. 选择一个您认为可行的方式来测试合约。 您可以使用NEAR CLI命令或运行现有的单元测试或模拟测试。如果有dApp的话，甚至可以使用网页界面来执行测试。
```

2021-08-12 08:07 UTC, danielwpz commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +    - #1. [scavenger hunt](https://github.com/Learn-NEAR/workshop--exploring-assemblyscript-contracts#activityscavenger-hunt) through several AssemblyScript projects
```suggestion
    - #1. [动物猎手](https://github.com/Learn-NEAR/workshop--exploring-assemblyscript-contracts#activityscavenger-hunt)是一个AssemblyScript的例子
```

2021-08-12 08:09 UTC, danielwpz commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +    - #2. [debugging challenge](https://github.com/Learn-NEAR/workshop--exploring-assemblyscript-contracts#activitydebugging-challenge) to fix a few failing unit tests with broken contracts
```suggestion
    - #2. [debugging challenge](https://github.com/Learn-NEAR/workshop--exploring-assemblyscript-contracts#activitydebugging-challenge) 有一些未通过的测试用例需要修复
```

2021-08-12 08:09 UTC, danielwpz commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +* 审查您所选语言标记为“CORE Activity”的3个应用程序
```suggestion
* 阅读您所选的语言中标记为“CORE Activity”的3个应用程序
```

2021-08-12 08:10 UTC, merged

2021-08-19 03:50 UTC, danielwpz commented
评分：优秀
意见：绝大部分意思传达准确，但有少部分专有名词翻译有误，个别语句的通畅性需要加强

2021-08-19 04:23 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-3-writing-web3-near-certified-developer-level-1.md
> +* 查看同质和非同质代币Rust合约
查看同质和非同质化通证的Rust合约