Create near-ethereum
near-x/learn-near-community pull request #16
Opened 2021-07-05 03:14 UTC by wongxf

2021-07-06 09:12 UTC, MartinYeung5 commented on near-ethereum
> +然而，仅仅因为以太坊是智能合约和 DeFi 的第一平台，并不意味着它没有问题。 以太坊有一个明显的问题，那就是严重的可扩展性问题。 它只是无法扩展其网络。
然而，只是因为以太坊是智能合约和去中心化金融(DeFi)中排名第一的平台的話，并不意味着它没有问题。 以太坊存在一个明显的问题，那就是重大的可扩展性问题。 它目前是无法扩展其网络。

2021-07-06 10:38 UTC, MartinYeung5 commented on near-ethereum
> +这就是 NEAR 协议出现的地方。 NEAR 的 USP 是它使用利用分片的权益证明共识机制。 在我们深入研究之前，让我们先了解一下以太坊和 NEAR。
这就是 NEAR 协议出场的时候。 NEAR 的独特的卖点是它使用分片的权益证明共识机制。 在我们深入了解之前，让我们先认识一下以太坊和 NEAR。

2021-07-06 16:21 UTC, MartinYeung5 commented on near-ethereum
> +这就是 NEAR 协议出现的地方。 NEAR 的 USP 是它使用利用分片的权益证明共识机制。 在我们深入研究之前，让我们先了解一下以太坊和 NEAR。
补充一下, USP 是指Unique Selling Point, (如果有错，请更正) 
文中不常见的英文缩写也需尽量翻译成中文，方便读者可以真正了解文章的内容。

2021-07-07 01:20 UTC, wongxf commented on near-ethereum
> +这就是 NEAR 协议出现的地方。 NEAR 的 USP 是它使用利用分片的权益证明共识机制。 在我们深入研究之前，让我们先了解一下以太坊和 NEAR。
USP 建议翻译成    与众不同之处

2021-07-07 01:28 UTC, MartinYeung5 commented on near-ethereum
> +NEAR 🤝 以太坊
NEAR与以太坊
* 原文是一个握手的图案，如果把它换成文字会比较方便理解，而且也方便转發到其他平台。

2021-07-07 06:44 UTC, MartinYeung5 commented on near-ethereum
> +该协议基于与比特币相同的技术，并结合了数据库分片等功能。 NEAR 协议是从头开始构建的，是最终用户和开发人员最容易访问的网络，同时还确保了可扩展性和安全性。
该协议基于与比特币相同的技术，而且结合了数据库分片等特色。 NEAR 协议是从头开始构建的，而且是最终用户和开发人员最轻易进入使用的网络，同时还确保了可扩展性和安全性。

2021-07-07 06:44 UTC, MartinYeung5 commented on near-ethereum
> +大多数可扩展的区块链集中处理，将其限制在高端硬件上，这可以暂时提高其吞吐量，NEAR 允许平台以完全分散的方式线性扩展，最多可处理数十亿笔交易。
大多数可扩展的区块链是选择中心化的处理，将其限制在高端硬件上，这可以暂时提高其吞吐量，而NEAR 允许平台以完全去中心化的方式进行线性扩展，最多可处理数十亿笔交易。

2021-07-07 06:44 UTC, MartinYeung5 commented on near-ethereum
> +NEAR 由 NEAR 集体开发，这是一个由开发人员和研究人员组成的社区，合作构建该项目。 NEAR 的一些重要特性是
NEAR 由 NEAR 社区贡献者(the NEAR collective)开发，这是一个由开发人员和研究人员组成的社区，合作构建该项目。 NEAR 的一些重要特色是

2021-07-07 06:52 UTC, MartinYeung5 commented on near-ethereum
> +NEAR 由 NEAR 集体开发，这是一个由开发人员和研究人员组成的社区，合作构建该项目。 NEAR 的一些重要特性是
我在网上有查看了一些资料, the NEAR collective 是一个专称，所以从它所包含的意思进行翻译比较好。而且看到有人把the NEAR collective称为NEAR 社区贡献者，我觉得是挺合适的，加上在原文的解释也包含community，让人觉得比较像一个社区。
不知道大家觉得怎样?

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +在我们继续之前，让我们了解分片。 有时系统必须处理大量数据。 这会影响系统的性能，降低吞吐量并影响系统的性能。 分片通过对数据进行水平分区来克服这一点，使其更小、更易于管理，更重要的是，处理速度更快。
在我们继续之前，让我们了解分片。 有时系统必须处理大量数据。 这会影响系统的性能，降低吞吐量并影响系统的性能。 分片通过对数据进行水平分割来克服这一点，使其更小、更易于管理，更重要的是，处理过程更快。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +NEAR和以太坊：NEAR和以太坊是如何工作的？
NEAR和以太坊：NEAR和以太坊的工作原理？

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +以太坊不仅仅是一个进行交易的金融平台；它还支持分散应用程序和智能合约。以太坊基于区块链技术，使用一个公共账本来存储所有经过验证的交易。任何想要查看交易的人都可以访问这些交易，确保完全透明，同时确保存储在区块链中的数据不会被更改或操纵。
以太坊不仅仅是一个进行交易的金融平台；它还支持去中心分应用程式和智能合约。以太坊基于区块链技术，使用一个公共账本来存储所有经过验证的交易。任何想要查看交易的人都可以访问这些交易，确保完全透明，同时确保存储在区块链中的数据不会被更改或操纵。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +以太坊的区块链类似于比特币区块链，充当一个公共账本，记录所有交易和智能合约历史。全球志愿者存储整个以太坊区块链的副本，使区块链完全分散。每次在区块链上发生交易或智能合约等行为时，全球所有节点都会对其进行处理，确保遵守区块链规则。
以太坊的区块链类似于比特币区块链，充当一个公共账本，记录所有交易和智能合约历史。全球志愿者存储整个以太坊区块链的副本，使区块链完全去中心化。每次在区块链上发生交易或智能合约等动作时，全球所有节点都会对其进行处理，确保遵守区块链规则。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +所有节点都是连接的，并且遵循关于智能合约和交易的相同规则集。以太坊的节点还跟踪所有应用程序、用户余额和智能合约代码的状态，确保所有信息始终是最新的。
所有节点都是连接的，并且遵循关于智能合约和交易的同一套规则。以太坊的节点还保留所有应用程序、用户余额和智能合约代码的状态纪录，确保所有信息始终是最新的。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +借助 Solidity，开发人员可以编写智能合约来管理区块链上的交易及其结果。智能合约不同于传统合约，因为它们确保合同条款得到履行。此外，当一组预定条件得到满足时，它们会自动执行事务，从而消除任何事务中涉及的所有第三方。
借助 Solidity，开发人员可以编写智能合约来管理区块链上的交易及其结果。智能合约不同于传统合约，因为它们确保合同条款得到满足。此外，当一组预定条件得到满足时，它们会自动执行交易，从而排除涉及任何交易的所有第三方组织。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +NEAR使用区块链技术，就像以太坊和卡尔达诺等其他区块链一样。NEAR充当基础区块链，应用程序可以在其上构建和部署。它使用了一种被称为Nightshade的共识机制来帮助它实现高吞吐量。NEAR的一致性机制假设来自所有shard的事务组合成一个块，这就是为什么每个shard提交每个块的一个片段。这个片段称为块。
NEAR使用区块链技术，就像以太坊和卡尔达诺(Cardano) 等其他区块链一样。NEAR充当基础区块链，应用程序可以在其上构建和部署。它使用了一种被称为Nightshade的共识机制来帮助它达到高吞吐量。NEAR的共识机制假设来自所有分片的交易给合成一个区块，这就是为什么每个分片提交每个区块的一部分。这个部分称为碎块。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +验证程序是随机选择的，然后跨多个分片链处理事务，提高了NEAR协议的事务处理能力。区块被处理，然后存储在区块链上，完成交易。
验证者是被随机选择的，然后在多个分片链上处理交易，提高了NEAR协议的交易量。所有碎块被处理后，会存储在区块链上以完成交易。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +NEAR并不是基于每个节点都必须处理整个代码的思想来运行的。相反，它通过使用分片来解决可伸缩性问题。通过分片，数据被水平分区，使得管理更容易，处理更快。
NEAR并不是基于每个节点都必须处理整个代码的想法来运行的。相反，它通过使用分片来解决可扩展性问题。利用分片，数据被水平分割，使得管理更容易，处理过程更快。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +目前，以太坊使用工作量证明共识机制，但随着以太坊 2.0 的出现，该平台将转向权益证明共识机制。 Proof-of-Stake 将通过 Casper 协议实施，创建一个去信任的生态系统。在完全切换到 Proof-of-Stake 机制之前，以太坊将实施混合 PoW-PoS 共识机制。
目前，以太坊使用工作量证明 (PoW) 共识机制，但随着以太坊 2.0 的出现，该平台将转向权益证明(PoS)共识机制。权益证明将通过 Casper 协议实行，创建一个去信任的生态系统。在完全切换到权益证明机制之前，以太坊将实施混合 PoW-PoS 的共识机制。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +让我们了解工作量证明和权益证明的工作原理。工作量证明要求矿工相互竞争，利用大量计算能力解决复杂的数学问题来验证交易。一旦交易得到验证，矿工就会得到奖励。以太坊正在转向权益证明机制，因为工作量证明存在几个问题，例如高能耗。还进行了转换以解决以太坊的可扩展性问题。
让我们了解工作量证明和权益证明的工作原理。工作量证明要求矿工相互竞争，利用大量算力解决复杂的数学问题来验证交易。一旦交易得到验证，矿工就会得到相对应的奖励。以太坊正在转向权益证明机制，因为工作量证明存在几个问题，例如高能耗。这个转换同时解决以太坊的可扩展性问题。

2021-07-07 07:14 UTC, MartinYeung5 commented on near-ethereum
> +在权益证明共识机制中，验证者质押他们的 ETH，然后随机选择他们来证明一个区块。选定的验证者提出一个区块，而其他验证者需要证明他们已经看到了该区块。一旦他们验证了区块，它就会被添加到区块链中，验证者就会得到奖励。因此，验证者会因提议和证明区块而获得奖励。
在权益证明共识机制中，验证者质押他们的 ETH，然后随机选择他们来证明一个区块。选定的验证者产生一个区块，而其他验证者需要证明他们已经看到了该区块。一旦他们验证了区块，它就会被添加到区块链中，验证者就会得到奖励。因此，验证者会因产生和证明区块而获得奖励。

2021-07-07 07:44 UTC, MartinYeung5 commented on near-ethereum
> +但是，Nightshade 将系统视为单个区块链，每个区块都包含所有分片的交易。然而，参与者不需要下载完整的状态，而是只维护作为他们验证交易的分片一部分的状态。创建每个区块中所有交易的列表，然后将其拆分为多个块，每个分片分配一个分片。
但是，Nightshade 将系统视为单个区块链，每个区块都包含所有分片的交易。然而，参与者不需要下载完整的状态，而是只维护作为他们验证交易的分片一部分的状态。创建每个区块中所有交易的列表，然后将交易列表拆分为多个碎块，每个碎块中的分片会被分配另一个分片。

2021-07-07 08:30 UTC, MartinYeung5 commented on near-ethereum
> +验证者是 NEAR 协议的关键部分，保持对协议的共识。因此，他们需要始终保持系统更新，同时保持服务器在线。
验证者是 NEAR 协议的关键部分，保持对协议的共识。因此，他们需要一直保持系统在最新状态，同时保持服务器在线。

2021-07-07 08:33 UTC, MartinYeung5 commented on near-ethereum
> +验证者可以通过重新抵押他们的代币和奖励来再次注册。
验证者可以通过重新抵押他们的通证和奖励来再次参加。

2021-07-07 08:33 UTC, MartinYeung5 commented on near-ethereum
> +验证者可以通过两种方式加强他们的权益，购买代币或通过权益委托借入代币。
验证者可以通过两种方式加强他们的权益，购买通证或通过权益委托借入通证。

2021-07-07 08:35 UTC, MartinYeung5 commented on near-ethereum
> +尽管 NEAR 的主网是在一年多前推出的，但有几个平台正在其上构建。 NEAR 协议的一些项目是
尽管 NEAR 的主网是在一年多前推出的，但只有数个平台正在其上构建。 运用NEAR 协议的一些项目有:

2021-07-07 08:41 UTC, MartinYeung5 commented on near-ethereum
> +以太坊现在正在转向以太坊 2.0 或 Serenity。升级将明显提高区块链的可扩展性、效率和以太坊区块链的速度。此外，升级将使以太坊能够降低燃料成本并处理更多交易，在不影响安全性的情况下提高区块链的可扩展性。
以太坊现在正在转向以太坊 2.0 或 Serenity。升级将明显提高区块链的可扩展性、效率和以太坊区块链的速度。此外，升级将使以太坊能够降低gas费用并处理更多交易，在不影响安全性的情况下提高区块链的可扩展性。

2021-07-07 08:45 UTC, MartinYeung5 commented on near-ethereum
> +NEAR 和以太坊：代币
NEAR 和以太坊：通证

2021-07-07 08:49 UTC, MartinYeung5 commented on near-ethereum
> +链环
链环 (Chainlink)

2021-07-07 09:03 UTC, MartinYeung5 commented on near-ethereum
> +极光在NEAR上的应用
极光(Aurora)在NEAR协议上的应用

2021-07-07 13:11 UTC, MartinYeung5 commented on near-ethereum
> +由于 NEAR 的分片协议，验证者无需下载复杂的软件即可加入平台。然后他们可以通过验证网络上的交易来赚取代币。
由于 NEAR 的分片协议，验证者无需下载复杂的软件即可加入平台。他们可以通过验证网络上的交易来赚取通证。

2021-07-07 13:11 UTC, MartinYeung5 commented on near-ethereum
> +随着以太坊到 NEAR 桥（也称为彩虹桥）的推出，用户可以将他们的以太坊 ERC-20 代币桥接到 NEAR，并开始在 NEAR 的去中心化应用生态系统中使用它们。 这一发展是朝着让平台尽可能易于访问的创始团队愿景迈出的一大步。
随着以太坊到 NEAR 桥（也称为彩虹桥）的推出，用户可以将他们的以太坊 ERC-20 通
证桥接到 NEAR，并开始在 NEAR 的去中心化应用生态系统中使用它们。 这个發展是向着创始团队的愿景在平台的可使用性上迈出一大步。

2021-07-07 13:11 UTC, MartinYeung5 commented on near-ethereum
> +NEAR 还致力于实施以太坊虚拟机 (EVM) 支持。 此过程完成后，开发人员可以在 NEAR 上重新部署他们的 dApp，只需进行最少的更改，并启用跨链启动。
NEAR 也致力于实行对以太坊虚拟机 (EVM)的支持。 此过程完成后，开发人员可以以最少的改动在 NEAR 上重新部署他们的 dApp，而且能够启动跨链。

2021-07-07 13:11 UTC, MartinYeung5 commented on near-ethereum
> +NEAR 协议宣布与 Chainlink 建立合作伙伴关系，同时推出彩虹桥，允许 NEAR 和以太坊互动。
NEAR 协议宣布与 Chainlink 建立合作伙伴关系，同时推出彩虹桥，允许 NEAR 和以太坊之间的交流。

2021-07-07 13:11 UTC, MartinYeung5 commented on near-ethereum
> +NEAR协议已经显示出很大的潜力，它利用分片来解决第二代区块链的可伸缩性问题。此外，NEAR在不影响平台安全性的情况下显著提高了吞吐量。
NEAR协议已经展示出很多的承诺，它利用分片来解决第二代区块链的可扩展性的问题。此外，NEAR在没有放弃平台安全性的情况下明显地提高了吞吐量。

2021-07-07 13:11 UTC, MartinYeung5 commented on near-ethereum
> +感谢 NEAR 集体，数百名区块链工程师和开发人员正在致力于 24*7 全天候改进协议。 NEAR 还推出了其主网，该网络已准备好支持 dApps 和其他服务。 NEAR 专注于确保 NEAR 平台易于验证者、最终用户和开发人员使用，因此已成为智能合约平台领域的一股力量。
由于NEAR社区贡献者(the NEAR collective)的存在，数百名区块链工程师和开发人员可以全天候地努力改进协议。 NEAR 也推出了其主网，而该网络已准备好支持 dApps 和其他服务。 NEAR 集中于确保 NEAR 平台对验证者、最终用户和开发人员都是容易使用的，因此已成为智能合约平台领域的一股力量。

2021-07-08 12:59 UTC, wongxf commented on near-ethereum
> +NEAR 由 NEAR 集体开发，这是一个由开发人员和研究人员组成的社区，合作构建该项目。 NEAR 的一些重要特性是
挺好

2021-07-12 01:16 UTC, wongxf commented on near-ethereum
> +在我们继续之前，让我们了解分片。 有时系统必须处理大量数据。 这会影响系统的性能，降低吞吐量并影响系统的性能。 分片通过对数据进行水平分区来克服这一点，使其更小、更易于管理，更重要的是，处理速度更快。
我觉得处理速度更快读取来更通顺

2021-07-12 04:51 UTC, MartinYeung5 commented on near-ethereum
> +在我们继续之前，让我们了解分片。 有时系统必须处理大量数据。 这会影响系统的性能，降低吞吐量并影响系统的性能。 分片通过对数据进行水平分区来克服这一点，使其更小、更易于管理，更重要的是，处理速度更快。
也可以的
但在分區那個，我覺得用分割可能好一點。 因為是把資料分割成更小的"表"來進行，像用一把刀把表去切成不同小的"表"。

2021-07-12 06:53 UTC, think-in-universe commented
修改建议：

1. Markdown 展示的格式应该与原文一致：Markdown 语法可以参考 https://guides.github.com/features/mastering-markdown/
2. 修改文章的路径到  cn/resources/guides 文件夹下

2021-07-21 03:26 UTC, wongxf reviewed
> 修改建议：
> 
> 1. Markdown 展示的格式应该与原文一致：Markdown 语法可以参考 https://guides.github.com/features/mastering-markdown/
> 2. 修改文章的路径到  cn/resources/guides 文件夹下

已经修改完成

2021-07-22 08:43 UTC, danielwpz requested changes

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +如果你在其网站上查看以太坊的定义，它是这样的——
```suggestion
如果你在其网站上查看以太坊的定义，它是这样说的——
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +升级还将使以太坊转向权益证明共识机制。 PoS 将看到通过算法选择的验证者为平台提供安全性。验证者将通过锁定他们的 ETH 来保护平台。任何违背平台利益的验证者都将削减其权益份额，确保平台的安全。
’PoS 将看到通过算法选择的验证者为平台提供安全性。‘这句话明显不通顺麻烦在修改一下

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +NEAR 协议诞生于 2018 年夏天。 一个去中心化的开发平台，该协议旨在为去中心化应用程序创造完美的环境，专注于应对其他平台的智能合约和 dApp 领域中的缺点。这些缺点主要是低速、低吞吐量以及与其他链的兼容性差的问题。
```suggestion
NEAR 协议诞生于 2018 年夏天。 一个去中心化的开发平台，该协议旨在为去中心化应用程序创造完美的环境，专注于应对其他平台的智能合约和 dApp 领域中的缺点，主要包括低速、低吞吐量以及与其他链的兼容性差的问题。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +它还引入了 2019 年提出的名为“Doomslug”的区块生成机制。 Doomslug 允许实用确定性或“Doomslug”确定性，确保区块在几秒钟内获得确定性。
```suggestion
它还引入了 2019 年提出的名为“Doomslug”的区块生成机制。 Doomslug 采用了实用（即Doomslug）确定性，确保区块在几秒钟内获得确定性。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +大多数可扩展的区块链是选择中心化的处理，将其限制在高端硬件上，这可以暂时提高其吞吐量，而NEAR 允许平台以完全去中心化的方式进行线性扩展，最多可处理数十亿笔交易。
```suggestion
大多数可扩展的区块链选择中心化的计算资源，将其限制在高端硬件上，这可以暂时提高其吞吐量，而NEAR 允许平台以完全去中心化的方式进行线性扩展，最多可处理数十亿笔交易。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +**什么是 NEAR 集体？**
讨论了一下，Near Collective就用英文就可以，不用专门翻译了

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +NEAR 集体由不断致力于改进 NEAR 协议的个人组织和其他贡献者组成。 该集体致力于为 NEAR 网络编写初始代码和实现等项目。 NEAR 是完全去中心化的，独立运行，不能被关闭或操纵，即使是那些构建它的人。
```suggestion
NEAR  Collective由不断致力于改进 NEAR 协议的个人组织和其他贡献者组成。 其致力于为 NEAR 网络编写初始代码和实现等项目。 NEAR 是完全去中心化的，独立运行，不能被关闭或操纵，即使是那些构建它的人。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +NEAR 集体 拥有 NEAR 基金会等成员。 NEAR 基金会是一个非营利组织，致力于围绕 NEAR 区块链创建一个充满活力的生态系统。 它有助于协调治理活动和发展。 NEAR 集体有多个项目，NEAR 区块链只是该集体支持的几个项目之一。
```suggestion
NEAR 集体 拥有 NEAR 基金会等成员。 NEAR 基金会是一个非营利组织，致力于围绕 NEAR 区块链创建一个充满活力的生态系统。 它有助于协调治理活动和发展。 NEAR Collective有多个项目，NEAR 区块链只是该组织支持的几个项目之一。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +借助 Solidity，开发人员可以编写智能合约来管理区块链上的交易及其结果。智能合约不同于传统合约，因为它们确保合同条款得到履行。此外，当一组预定条件得到满足时，它们会自动执行事务，从而消除任何事务中涉及的所有第三方。
```suggestion
借助 Solidity，开发人员可以编写智能合约来管理区块链上的交易及其结果。智能合约不同于传统合约，因为它们确保合同条款得到履行。此外，当一组预定条件得到满足时，它们会自动执行事务，而不需要任何第三方的介入。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +验证者是被随机选择的，然后在多个分片链上处理交易，提高了NEAR协议的交易量。所有碎块被处理后，会存储在区块链上以完成交易。
```suggestion
验证者是被随机选择的，然后在多个分片链上处理交易，提高了NEAR协议的交易量。所有分块被处理后，会存储在区块链上以完成交易。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +NEAR并不是基于每个节点都必须处理整个代码的想法来运行的。相反，它通过使用分片来解决可扩展性问题。利用分片，数据被水平分割，使得管理更容易，处理过程更快。
```suggestion
NEAR并不是基于每个节点都必须处理所有代码的想法来运行的。相反，它通过使用分片来解决可扩展性问题。利用分片，数据被水平分割，使得管理更容易，处理过程更快。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +但是，Nightshade 将系统视为单个区块链，每个区块都包含所有分片的交易。然而，参与者不需要下载完整的状态，而是只维护作为他们验证交易的分片一部分的状态。创建每个区块中所有交易的列表，然后将交易列表拆分为多个碎块，每个碎块中的分片会被分配另一个分片。
```suggestion
但是，Nightshade 将系统视为单个区块链，每个区块都包含所有分片的交易。然而，参与者不需要下载完整的状态，而是只维护作为他们验证交易的分片一部分的状态。创建每个区块中所有交易的列表，然后将交易列表拆分为多个块，每个分片会被分配到一个块上。
```
这里原文应该是笔误了

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +NEAR 的原生代币,NEAR 代币用于激励网络上的验证者。 令牌还能驱动区块链上的交易和智能合约。 由于 NEAR 是一个社区治理平台，代币持有者在NEAR平台的治理中发挥着重要作用，对NEAR平台上的潜在变化进行投票。
```suggestion
NEAR 的原生代币,NEAR 代币用于激励网络上的验证者。 代币还能驱动区块链上的交易和智能合约。 由于 NEAR 是一个社区治理平台，代币持有者在NEAR平台的治理中发挥着重要作用，对NEAR平台上的潜在变化进行投票。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +在去中心化应用程序和去中心化金融方面，以太坊处于领先地位，在其区块链上运行着 3000 多个 dApp。 以太坊的大多数项目都集中在def上，扩展加密货币的用途，以满足更复杂的金融用途。
```suggestion
在去中心化应用程序和去中心化金融方面，以太坊处于领先地位，在其区块链上运行着 3000 多个 dApp。 以太坊的大多数项目都集中在DeFi上，扩展加密货币的用途，以满足更复杂的金融用途。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +极光(Aurora)也在NEAR 协议上推出，提供以太坊第 2 层体验，是一种允许开发人员接触其他市场的解决方案，极光(Aurora)利用 NEAR 协议的特色，例如 gas 费用补偿和分片。它在两个关键组件上运行，分別是 Aurora Bridge 和 Aurora Engine。
```suggestion
极光(Aurora)也在NEAR 协议上推出，是一种允许开发人员接触其他市场的以太坊2层解决方案。极光(Aurora)利用了 NEAR 协议的特色，例如 gas 费用补偿和分片。它在两个关键组件上运行，分別是 Aurora Bridge 和 Aurora Engine。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +   * 极光通过 NEAR 协议提供与以太坊的不妥协兼容性。
```suggestion
   * 极光通过 NEAR 协议与以太坊进行兼容。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +   * 灵活的用户体验和对在 NEAR 平台上运行的服务的访问还具有简单的入门流程。
* 灵活的用户体验和对在 NEAR 平台上运行的服务的访问还具有简单的入门流程。
不通顺

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +NEAR协议已经展示出很多的承诺，它利用分片来解决第二代区块链的可扩展性的问题。此外，NEAR在没有放弃平台安全性的情况下明显地提高了吞吐量。
```suggestion
NEAR协议已经展示出诸多的可能性，它利用分片来解决第二代区块链的可扩展性的问题。此外，NEAR在没有放弃平台安全性的情况下明显地提高了吞吐量。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +由于NEAR社区贡献者(the NEAR collective)的存在，数百名区块链工程师和开发人员可以全天候地努力改进协议。 NEAR 也推出了其主网，而该网络已准备好支持 dApps 和其他服务。 NEAR 集中于确保 NEAR 平台对验证者、最终用户和开发人员都是容易使用的，因此已成为智能合约平台领域的一股力量。
```suggestion
由于NEAR Collective的存在，数百名区块链工程师和开发人员可以全天候地努力改进协议。 NEAR 也推出了其主网，而该网络已准备好支持 dApps 和其他服务。 NEAR 集中于确保 NEAR 平台对验证者、最终用户和开发人员都是容易使用的，因此已成为智能合约平台领域的一股力量。
```

2021-07-22 08:43 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +另一方面，由于其令人羡慕的开发者社区以及蓬勃发展的 DeFi 和 NFT 生态系统，以太坊保持了其宝座的地位。 这两种协议都为开发人员构建未来的去中心化生态系统提供了一个绝佳的平台。
```suggestion
至于以太坊，由于其令人羡慕的开发者社区以及蓬勃发展的 DeFi 和 NFT 生态系统，以太坊保住了其宝座的地位。 这两种协议都为开发人员构建未来的去中心化生态系统提供了一个绝佳的平台。
```

2021-07-23 01:38 UTC, wongxf commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +   * 灵活的用户体验和对在 NEAR 平台上运行的服务的访问还具有简单的入门流程。
我修改成这样，你看如何。灵活的用户体验（UX）和访问NEAR平台上的服务提供简单入门流程。

2021-07-23 08:21 UTC, danielwpz commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +   * 灵活的用户体验和对在 NEAR 平台上运行的服务的访问还具有简单的入门流程。
嗯我觉得要不可以这样：
用户体验（UX）很灵活，并且访问Near平台上的服务也很简单

2021-07-23 08:24 UTC, danielwpz commented
@wongxf 以上还有两个地方麻烦再修改一下哈

2021-07-23 09:19 UTC, MartinYeung5 commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +升级还将使以太坊转向权益证明共识机制。 PoS 将看到通过算法选择的验证者为平台提供安全性。验证者将通过锁定他们的 ETH 来保护平台。任何违背平台利益的验证者都将削减其权益份额，确保平台的安全。
"PoS will see validators who have been chosen algorithmically provide security to the platform. "
利用POS可以看到所有验证者是被算法选择，以向平台提供安全性

2021-07-23 09:29 UTC, MartinYeung5 commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +升级还将使以太坊转向权益证明共识机制。 PoS 将看到通过算法选择的验证者为平台提供安全性。验证者将通过锁定他们的 ETH 来保护平台。任何违背平台利益的验证者都将削减其权益份额，确保平台的安全。
```suggestion
升级还将使以太坊转向权益证明共识机制。通过POS可以看到所有验证者是被算法选择，以向平台提供安全性。验证者将通过锁定他们的 ETH 来保护平台。任何违背平台利益的验证者都将削减其权益份额，确保平台的安全。
```

2021-07-23 10:46 UTC, MartinYeung5 commented on cn/resources/guides/NEAR 🤝 Ethereum.md
> +但是，Nightshade 将系统视为单个区块链，每个区块都包含所有分片的交易。然而，参与者不需要下载完整的状态，而是只维护作为他们验证交易的分片一部分的状态。创建每个区块中所有交易的列表，然后将交易列表拆分为多个碎块，每个碎块中的分片会被分配另一个分片。
我看過原文, 它的意思可能指而sub shard, 也有可能指每個碎塊會被分配到其他分片上，
也可能是指每個shard都被分配一個驗證者。

我在NEAR的其他文章看到有關Nightshade中shard的相關描述:
Each block contains one or zero chunks per shard,
所以是chunk被分配到shard

相關文章:
https://near.org/papers/nightshade/#nightshade

2021-07-27 00:43 UTC, wongxf commented
> @wongxf 以上还有两个地方麻烦再修改一下哈

已修改

2021-07-28 10:22 UTC, merged

2021-08-14 03:18 UTC, MartinYeung5 commented
翻译质量评价: 较差
另外，我发现有不少地方仍存在问题，例如: 81, 110 (token翻译为通证比较好), 114行等， 而且还有其他地方都未有修改，建议再重新看一遍。

2021-08-17 02:05 UTC, wongxf commented
翻译质量评价: 优秀

2021-08-19 07:10 UTC, danielwpz commented
翻译质量：一般
本文内容比较多，总体上还是能把大部分东西正确翻译的。但是还是有不少明显很生涩的语句需要以后在提高，比如“协议提供与以太坊的不妥协兼容性”这个翻译太过于生硬了。

2021-08-19 07:28 UTC, wongxf commented
好的，我会继续努力提高