Step 4 testing web3 near certified developer level 1
near-x/learn-near-community pull request #17
Opened 2021-07-05 15:33 UTC by shepf

2021-07-29 04:55 UTC, think-in-universe requested changes

2021-07-29 04:55 UTC, think-in-universe commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +>What is a new idea — what Satoshi figured out — is how to independently agree upon a history of events without central coordination. He found a way to implement a decentralised timestamping scheme t
未翻译，请翻译完成后再次提交审阅

2021-07-29 04:56 UTC, think-in-universe commented
这个 PR 不应该包含对 What is NEAR Protocol 的改动

2021-07-29 07:44 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +> :sparkles: 今天的目标是编写可以合约的单元测试和模拟测试。:sparkles:
```suggestion
> :sparkles: 今天的目标是编写一个测试来通过你的合约。:sparkles: 
```

2021-07-29 07:46 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +在下面的资源章节中，选择AssemblyScript或Rust
```suggestion
在下面的资源部分中，选择AssemblyScript或Rust
```

2021-07-29 07:49 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +* 为标记为“CORE Activity”的3个合约写上3~5个单元测试
`WRITE 3-5 unit tests for each contract listed as CORE Activity`
为CORE Activity中的每个合约编写3-5个单元测试

2021-07-29 09:14 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +* 您**确实**需要构建（并运行测试）（如果可以）每个dApp（“去中心化应用”）
```suggestion
* 您**确实**需要构建（并运行测试）（如果可以）每个合约
```

2021-07-29 09:16 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +如果你想专注于AssemblyScript，[ OPEN the list of AssemblyScript contracts ](https://airtable.com/shrG4kGx80F55usI4)
未翻譯

2021-07-29 09:21 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +b)验证测试如预期通过(测试可以通过命令行运行)
```suggestion
b)验证测试以通过预期效果(测试可以通过命令行运行)
```

2021-07-29 09:22 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +单元测试是由[as- aspect](https://github.com/jtenner/as-pect)提供的，语法类似于RSpec。这个库有很好的[文档](https://tenner-joshua.gitbook.io/as-pect/)记录，但有时[tests for the testing library](https://github.com/jtenner/as-pect/tre
未翻譯

2021-07-29 09:26 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +[near.dev](https://examples.near.org/) 上几乎所有可用的示例都包括单元测试。
```suggestion
絕大部份示例都在[near.dev](https://examples.near.org/)上，包括单元测试。
```

2021-07-29 09:43 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +* 按预期验证测试通过（测试可以通过IDE或命令行运行）
```suggestion
* b)验证测试以通过预期效果(测试可以通过IDE或命令行运行)
```

2021-07-29 09:44 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +单元测试包括Rust语言的一部分。
```suggestion
单元测试是Rust语言的一部分。
```

2021-07-29 09:53 UTC, MartinYeung5 commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +如果您想看到一些更好的例子,所有NEAR的[核心合约](https://github.com/near/core-contracts) 都包括单元测试。 例如，您可以看白名单合约。例如，[test_utils](https://github.com/near/core-contracts/blob/master/whitelist/src/tests/test_utils.rs#L21)，该导入
```suggestion
如果您想看到一些更好的例子,所有NEAR的[核心合约](https://github.com/near/core-contracts) 都包括单元测试。 例如，您可以看白名单合约。包括 [test_utils](https://github.com/near/core-contracts/blob/master/whitelist/src/tests/test_utils.rs#L21)，会以独立文件的形式为所有单元测试导入入MockedBlockchain上下文的设置。
```

2021-07-31 09:30 UTC, tigerjibo commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +### :green_book: 核心活动：
```suggestion
### :green_book: 关键活动：
```

2021-07-31 09:30 UTC, tigerjibo commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +在下面的资源章节中，选择AssemblyScript或Rust
```suggestion
在下面的参考资料部分中选择AssemblyScript或Rust
```

2021-07-31 09:37 UTC, tigerjibo approved these changes

2021-07-31 09:37 UTC, tigerjibo commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +>What is a new idea — what Satoshi figured out — is how to independently agree upon a history of events without central coordination. He found a way to implement a decentralised timestamping scheme t
```suggestion
>中本聪提出的一个新想法是，在没有中央协调的情况下，如何独立地就事件的历史达成一致。他找到了一种实现分布式时间戳计划的方法:
```

2021-07-31 09:37 UTC, tigerjibo commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +> a) doesn’t require a time-stamping company or server,
```suggestion
> a) 不需要时间戳公司或服务器,
```

2021-07-31 09:37 UTC, tigerjibo commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +> b) doesn’t require a newspaper or any other physical medium as proof, and
```suggestion
> b)不需要报纸或任何其他物理介质作为证明，而且
```

2021-07-31 09:37 UTC, tigerjibo commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +> c) can keep the ticks more-or-less constant, even when operating in an environment of ever-faster CPU clock times.
```suggestion
> c) 即使在CPU时钟时间越来越快的环境中操作，也可以或多或少地保持节拍恒定。
```

2021-07-31 09:37 UTC, tigerjibo commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +> – Gigi in Bitcoin is Time
```suggestion
> – Gigi在[比特币时代](https://dergigi.com/2021/01/14/bitcoin-is-time/)
```

2021-08-12 08:19 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +## 步骤4 – 测试 web3（NEAR开发者L1认证）
```suggestion
## 步骤4 – 测试web3合约（NEAR开发者L1认证）
```

2021-08-12 08:21 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +在下面的资源部分中，选择AssemblyScript或Rust
```suggestion
在下面的参考资料部分中，选择AssemblyScript或Rust
```

2021-08-12 08:21 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +* 为标记为“CORE Activity”的3个合约写上3~5个单元测试
```suggestion
* 为CORE Activity中的每个合约编写3-5个单元测试
```

2021-08-12 08:22 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +如果您需要更多有关此挑战的想法，请考虑以下事项：
```suggestion
如果您需要更多的挑战，请考虑以下事项：
```

2021-08-12 08:22 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +3. 看看这个小难题，对您来说可能很有趣
```suggestion
3. 看看这个挑战问题，对您来说可能很有趣
```

2021-08-12 08:23 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +4. 从空白文档（或只是模板代码）开始，然后尝试测试驱动（TDD）合约。
```suggestion
4. 从零开始（或只是模板代码），然后尝试使用测试驱动的方法（TDD）编写合约。
```

2021-08-12 08:24 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +模拟测试是一项不断发展演进的工作，我们为您提供了一些示例帮助。 了解NEAR上的模拟测试的关键在于测试**Wasm二进制文**件。 这意味着相同的模拟测试配置将适用于Rust和AssemblyScript。
```suggestion
模拟测试是一项不断发展演进的工作，我们为您提供了一些示例帮助。 了解NEAR上的模拟测试的关键在于测试**Wasm二进制文件**。 这意味着相同的模拟测试将同时适用于Rust和AssemblyScript。
```

2021-08-12 08:24 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +实际上，可以对已编译的Rust或已编译的AssemblyScript合约使用完全相同的模拟测试。 一旦您考虑到模拟测试使用的是相同的链上虚拟机，就恨容易理解。因此您在模拟测试中所做的一切都应该在1：1链上虚拟机可重复的。
```suggestion
实际上，可以对已编译的Rust或已编译的AssemblyScript合约使用完全相同的模拟测试。 一旦您考虑到模拟测试使用的是相同的链上虚拟机，就很容易理解。因此您在模拟测试中所做的一切都应该在1：1的链上虚拟机上重复。
```

2021-08-12 08:25 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +* [NEARly Neighbors](https://learn-near.github.io/nearly-neighbors) 有模拟测试
```suggestion
* [NEARly Neighbors](https://learn-near.github.io/nearly-neighbors) 
```

2021-08-12 08:25 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +* [Workshop on Cross-contract Calls](https://bit.ly/near-xcc) 有模拟测试
```suggestion
* [Workshop on Cross-contract Calls](https://bit.ly/near-xcc) 
```

2021-08-12 08:26 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +注意：今天的活动
```suggestion
注意：
```

2021-08-12 08:27 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +至少3份被标记为核心活动的合同
```suggestion
至少3份被标记为**CORE Activity**的合同
```

2021-08-12 08:29 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +[near.dev](https://examples.near.org/) 上几乎所有可用的示例都包括单元测试。
```suggestion
[near.dev](https://examples.near.org/) 上几乎所有的示例都包括单元测试。
```

2021-08-12 08:30 UTC, danielwpz commented on cn/resources/ncd/level1/step-4-testing-web3-near-certified-developer-level-1.md
> +您可以通过[Rust by Example](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html) 或 [“the book”](https://doc.rust-lang.org/book/ch11-01-writing-tests.html) 阅读更多有关单位测试。
```suggestion
您可以通过[Rust by Example](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html) 或 [“the book”](https://doc.rust-lang.org/book/ch11-01-writing-tests.html) 阅读更多有关单元测试的内容。
```

2021-08-12 08:32 UTC, merged

2021-08-19 03:52 UTC, danielwpz commented
评分：优秀
意见：绝大部分意思传达准确，但有少部分专有名词翻译有误，个别语句的通畅性需要加强