Create Intro – NEAR Certified Developer Level 1
near-x/learn-near-community pull request #19
Opened 2021-07-06 02:37 UTC by wongxf

2021-07-16 10:04 UTC, MartinYeung5 commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +简介-NEAR 1级开发人员认证
https://learnnear.club/lessons/intro-near-certified-developer-level-1/ 會自動導向至
https://learnnear.club/courses/near-certified-developer-level-1/

所以是不是已經在官網的內容有所更新了?

2021-07-21 03:38 UTC, wongxf commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +简介-NEAR 1级开发人员认证
使用near账户登陆后就不会自动转了。

2021-07-29 04:12 UTC, think-in-universe commented
请修改文档格式与原文保持一致后再提交审阅：https://learnnear.club/lessons/intro-near-certified-developer-level-1/

2021-07-29 13:03 UTC, think-in-universe commented
请修改标题的格式，可以使用 `### heading` 语法

2021-08-02 09:13 UTC, think-in-universe commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> + <font color=#F4A460 > NEAR认证开发者（一级）>介绍 </font> – <font color=#F4A460 > NEAR 认证开发人员 1 级 </font>
【开发人员】还是用【开发者】吧

2021-08-06 02:56 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +原文链接:https://learnnear.club/lessons/intro-near-certified-developer-level-1/
这个链接是不是写错了？打开之后不是这一页

2021-08-06 03:05 UTC, danielwpz requested changes
这篇文章的翻译是机翻的吧，而且没有人工完善过。
比如以下一些语句明显不是正常人翻的：
```
## 问题
所有问题都应发布到 2 个 Discord 频道之一：

＃帮助
问题：一般物流、一般时间表、帐户问题等

#step-#（第 1 步、第 1 步等）
分配支持，混淆re：步骤的一些主题等
```

希望译者可以全部重新审核一遍，我们十分尊重大家宝贵的时间和工作，也希望大家可以认真对待这个事情。如果短时间内没有明显的质量提升，我会关闭这个PR并且请其他人进行翻译。

2021-08-06 03:05 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +1.请使用专用的Discord服务器加入我们。
这是机翻？

2021-08-09 02:16 UTC, wongxf commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +1.请使用专用的Discord服务器加入我们。
我会重新修订

2021-08-09 03:08 UTC, wongxf commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +1.请使用专用的Discord服务器加入我们。
人工翻译了，但是有些还不太会翻译，就机器翻了。

2021-08-09 08:49 UTC, danielwpz requested changes
提了一些建议你再看下

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +1.请使用专用的Discord服务器加入我们。
我觉得原文意思是
```suggestion
1.加入我们专属的Discord群组
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +2.关注Twitter上的Learn NEARhttps://twitter.com/LearnNear
```suggestion
2.关注Twitter上的Learn NEAR：https://twitter.com/LearnNear
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +很高兴你能加入我们。我们将共同学习在智能合约平台NEAR 协议上构建分散的应用程序。
```suggestion
很高兴你能加入我们。我们将共同学习在智能合约平台NEAR上构建去中心化的应用程序。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +这是一门 NEAR L2E（Learn-to-Earn）课程，意义是：我们付钱让您完成课程。
```suggestion
这是一门 NEAR L2E（Learn-to-Earn）课程，也就是说：我们付钱让您完成课程。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +在本周开始之前,请先确保您熟悉其中的一些基础知识。尽管您不需要成为这些技术的专家，但克隆 NodeJS 项目、下载其依赖项并运行一些脚本应该没有问题。
```suggestion
在本周开始之前,请先确保您熟悉一些基础知识。尽管您不需要成为这些技术的专家，但您需要会克隆 NodeJS 项目、下载其依赖项并运行一些脚本。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +* **部署**合约和合理的用户界面
```suggestion
* **部署**合约和用户界面
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +该课程将包括大量的听力、观看、阅读和写作。
```suggestion
该课程将包括大量的观看、阅读和写作内容。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +* 我们将在本月最后一个星期五东部时间上午 11 点举行 60 分钟的演示日现场会议
```suggestion
* 我们将在每月最后一个星期五上午 11 点（东部时间）举行 60 分钟的视频演示
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +* 我们每天都会和我们的小团体见面，共同进步，分享困惑，一起提高！我们的时刻
```suggestion
* 我们每天都会和我们的小团体见面，共同进步，分享困惑，一起提高！
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +问题反馈：通常问题、一般时间表、帐户问题等
```suggestion
问题反馈：一般问题、日程安排、帐户问题等
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +＃帮助
因为这个是特殊的discord群组名，所以不用翻译哈
```suggestion
#help
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +#step-#（第 1 步、第 1 步等）
```suggestion
#step-#（如step-1, step-2等）
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +分配支持，困扰反馈：步骤的一些主题等
```suggestion
课后作业支持，疑难解答，每个步骤的一些相关主题等
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +* 作业附加到 StepN 课程
```suggestion
* 每个步骤的课程都有附加作业
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +**录音**
```suggestion
**课程录像**
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +所有公开可用的录音都将在活动结束后的 24-48 小时内发布在这里。
```suggestion
所有公开可用的录像都将在活动结束后的 24-48 小时内发布在这里。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +没什么，事实上我们付钱给你完成这门课程。
```suggestion
并不收费，事实上我们付钱给你完成这门课程。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +不需要，但也不是那么容易，你应该每天预算 10 小时，不是开玩笑。
```suggestion
不需要，但也不是那么容易，你应该预计每天花 10 小时，不是开玩笑。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +* 如果您是刚从培训机构毕业或拥有不到 3 年专业经验的初级软件开发者，您应该每天预算 4-6 小时。
```suggestion
* 如果您是刚从培训机构毕业或拥有不到 3 年专业经验的初级软件开发者，您应该预计每天花4-6 小时。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +* 如果您是具有 5 年或以上专业经验的高级软件开发者，则每天应该预算大约 2-4 小时。
```suggestion
* 如果您是具有 5 年或以上专业经验的高级软件开发者，则每天应该预计花大约 2-4 小时。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +MacOS 和 Linux 将是最容易使用的操作系统。
```suggestion
MacOS 和 Linux 的开发体验最佳。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +Windows 可能证明具有挑战性，但如果您对此感到满意，请加入我们。
```suggestion
使用Windows可能具有挑战性，但如果您愿意尝试，请加入我们！
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +在这里没有赢的事情，因为我们都输了。欢迎朋友。
```suggestion
在这里我们不计输赢。欢迎加入。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +**5. 价格什么时候上涨？！**
```suggestion
**5. 币价什么时候上涨？！**
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +不，实际上鼓励作弊。让我们弄清楚一件事：如果你认真学习，那么从这里到那里最快的方法就是认识人，提出问题，查看一些答案，查看更多答案，复制一些示例，打破常规，最后，如果你很幸运，学到了一些新东西。
```suggestion
不，实际上鼓励作弊。让我们弄清楚一件事：如果你认真学习，那么有所收获的最快方法就是认识其他人，提出问题，找到答案，复制示例代码，打破常规，最后如果幸运的话你会学到一些东西。
```

2021-08-09 08:49 UTC, danielwpz commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +只是不要因为其他人的工作而受到赞扬，因为那是蹩脚的。
```suggestion
但是不要把他人的工作占为己有，这很拉胯。
```

2021-08-10 01:50 UTC, wongxf commented on cn/resources/ncd/level1/Intro – NEAR Certified Developer Level 1.md
> +＃帮助
你机智，我太笨了。

2021-08-11 07:37 UTC, danielwpz commented
@wongxf 还有两个地方没改哈，你看一下可以直接用我suggest的或者自己修改一下让句子通顺都可

2021-08-12 06:15 UTC, danielwpz approved these changes

2021-08-12 06:15 UTC, merged

2021-08-19 04:09 UTC, danielwpz commented
评分：一般
意见：基本意思传达准确，但有不少语句还是有不通畅的问题。以及希望之后可以通读理解全文每一句话之后再开始进行翻译。