what-is-near-protocol.md
near-x/learn-near-community pull request #20
Opened 2021-07-06 02:37 UTC by MartinYeung5

Finished the translation of chapter 1 to 6

2021-07-06 12:16 UTC, shepf commented on cn/resources/guides/what-is-near-protocol.md
> +以太坊凭智能合约成为第二代区块链平台。另外，开發人员能够透过智能合约对複杂的交易[进行编程](https://learnnear.club/near-certified-developer-program-ncd/)。更可以创建分散式应用程式(dApps)。透过dApps的应用，可以大大增加区块链的应用场景。
```suggestion
以太坊凭智能合约成为第二代区块链平台。另外，开发人员能够透过智能合约对复制的交易[进行编程](https://learnnear.club/near-certified-developer-program-ncd/)。更可以创建去中心化应用程式(dApps)。透过dApps的应用，可以大大增加区块链的应用场景。
```

2021-07-06 12:16 UTC, shepf commented on cn/resources/guides/what-is-near-protocol.md
> +# 什麽是 NEAR 协议？
文件多处的繁体 字，全局替换一下吧

2021-07-06 12:16 UTC, shepf commented on cn/resources/guides/what-is-near-protocol.md
> +它的技术是支持加密货币。区块鍊是一种技术，可以将交易记录安全地存储在点对点的网络上，而不是将它们存储在单一位置。世界各地的独立服务器，称为节点，组成了一个运行区块链的网络。
```suggestion
它的技术是支持加密货币。区块链是一种技术，可以将交易记录安全地存储在点对点的网络上，而不是将它们存储在单一位置。世界各地的独立服务器，称为节点，组成了一个运行区块链的网络。
```

2021-07-07 03:13 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol.md
> +以太坊凭智能合约成为第二代区块链平台。另外，开發人员能够透过智能合约对複杂的交易[进行编程](https://learnnear.club/near-certified-developer-program-ncd/)。更可以创建分散式应用程式(dApps)。透过dApps的应用，可以大大增加区块链的应用场景。
@shepf 原文中的 sophisticated 可以解释为複杂的，而不是复制的，所以改用复制就不太合理。
另外，分散式应用程式和去中心化应用程式的意思是一样，统一用法是好的，如果大家决定用去中心化应用程式表示dApps, 就在所有文章都用同一样的翻译。

2021-07-07 14:17 UTC, shepf commented on cn/resources/guides/what-is-near-protocol.md
> +以太坊凭智能合约成为第二代区块链平台。另外，开發人员能够透过智能合约对複杂的交易[进行编程](https://learnnear.club/near-certified-developer-program-ncd/)。更可以创建分散式应用程式(dApps)。透过dApps的应用，可以大大增加区块链的应用场景。
是复杂，是我打错了  ，都翻译成去中心化吧

2021-07-08 01:40 UTC, shepf approved these changes

2021-07-19 09:09 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +在进一步深入学习之前，让大家了解一些背景故事，看看区块链平台是如何随着时间發展。
`發展` -> `发展`

2021-07-19 09:29 UTC, danielwpz requested changes
还是有不少繁体字的问题，希望能统一修改一下

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +NEAR的主要任务是提供一个理想的平台，让应用程式运行在一个可访问的共享既安全的钱池，用家可以拥有自己的身份及数据资料。同时会将抗分割网络、无伺服器计算、分布式储存的特色结合成一种新型的平台。
1. `让应用程式运行在一个可访问的共享既安全的钱池`，这句话和原文有一些出入，原意应该是让程序可以访问到共享的且安全的资金池。希望在修改一下。
2. 用家 -> 用户

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +自从中本聪于 2008 年 10 月發布比特币白皮书以来，世界已经熟悉了会改变游戏规则的区块链技术。在过去的十年中，区块链经历了三个演进阶段。
繁体字问题

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +自从中本聪于 2008 年 10 月發布比特币白皮书以来，世界已经熟悉了会改变游戏规则的区块链技术。在过去的十年中，区块链经历了三个演进阶段。
`世界已经熟悉了会改变游戏规则的区块链技术`建议改为`xxx的区块链技术已被世界所熟知`

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +比特币是第一代区块链的完美例子。该区块链的目的是成为一个简单直接的支付系统。从“互联网货币”开始，比特币已成为最受欢迎的资产类别之一。但是，当提及 BTC 时就会出现一个重要问题。BTC是不能应付複杂的交易，因为这些交易可能有多层元数据和逻辑。
繁体字

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +比特币是第一代区块链的完美例子。该区块链的目的是成为一个简单直接的支付系统。从“互联网货币”开始，比特币已成为最受欢迎的资产类别之一。但是，当提及 BTC 时就会出现一个重要问题。BTC是不能应付複杂的交易，因为这些交易可能有多层元数据和逻辑。
`BTC是不能应付複杂的交易，因为这些交易可能有多层元数据和逻辑。` 建议把定语前置，类似改为： BTC无法应对包含元数据和逻辑的复杂交易

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +以太坊凭智能合约成为第二代区块链平台。另外，开發人员能够透过智能合约对複杂的交易[进行编程](https://learnnear.club/near-certified-developer-program-ncd/)。更可以创建去中心化应用程式(dApps)。透过dApps的应用，可以大大增加区块链的应用场景。
繁体字

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +以太坊凭智能合约成为第二代区块链平台。另外，开發人员能够透过智能合约对複杂的交易[进行编程](https://learnnear.club/near-certified-developer-program-ncd/)。更可以创建去中心化应用程式(dApps)。透过dApps的应用，可以大大增加区块链的应用场景。
以太坊凭智能合约成为第二代区块链平台，使得开发人员终于可以通过智能合约对复杂的交易进行编程

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +但区块链的發展一直与它的成长斗争，因为区块链一直存在严重的扩展性问题。例如: 比特币每秒的交易量为7笔，而以太坊每秒的交易量只有25笔。当同PayPal(每秒115笔)和Visa(每秒1700笔)比较，就相当不济。
繁体字问题

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +公道来说，最近出现了一些第二层(Layer-two)解决方案，例如: Lightning Network Raiden, Plasma Protocal等，来应对以太坊与比特币的扩展性问题。这裡的想法是在底层区块链上创建一个附加层，让主要的协议也可以委派重複和繁琐的任务。
`公道来说，`可以删掉我觉得，没有必要

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +公道来说，最近出现了一些第二层(Layer-two)解决方案，例如: Lightning Network Raiden, Plasma Protocal等，来应对以太坊与比特币的扩展性问题。这裡的想法是在底层区块链上创建一个附加层，让主要的协议也可以委派重複和繁琐的任务。
`the main protocol can delegate repetitive and cumbersome tasks too.`, 这句话我的理解是：让主协议可以把重复且繁琐的工作委托给二层网络来解决。你看看是不是可以修改一下

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +因此，这就是第三代区块链發挥价值的地方。
繁体字

2021-07-19 09:29 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +为了解决这个问题，NEAR 使用了一种在数据库世界中已经非常流行的技术-分片。如果适当运用，它可以允许网络容量随着网络中节点数量的增加而扩展，因此没有理论上的网络容量限制。最好的部分？分片是一种针对第一层可扩展性的技术。
```suggestion
为了解决这个问题，NEAR 使用了一种在数据库中已经非常流行的技术----分片。如果适当运用，它可以允许网络容量随着网络中节点数量的增加而扩展，因此没有理论上的网络容量限制。比所有二层网络解决方案更好的是分片是一种针对第一层网络可扩展性的技术。
```

2021-07-20 08:54 UTC, danielwpz requested changes

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +正如我们目前看到的，随着越来越多的节点进入以太坊和比特币生态系统，整个共识和验证过程需要更多的时间。现在，分片将如何帮助区块链？
```suggestion
正如我们目前看到的，随着越来越多的节点进入以太坊和比特币生态系统，整个共识和验证过程需要更多的时间。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +分片激活会發生什么？
```suggestion
分片会发生什么？
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +每个唯一的账户都在一个分片中，该分片中的账户只会与同一分片中的其他账户进行交易。
```suggestion
每个账户都存在于一个分片中，并且某个分片中的账户只能与同一分片中的其他账户进行交易。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +有一个虚拟网络具有三个节点 - A、B 和 C，它们必须验证数据 T。数据 T 被分解为三个分片 T1、T2 和 T3。不是所有这些节点都是作为一个整体在 T 上工作，它们可以同时单独在一个分片上工作。如你所看到的，你所节省的时间会是指数级。
```suggestion
有一个虚拟网络具有三个节点 - A、B 和 C，它们必须验证数据 T。数据 T 被分解为三个分片 T1、T2 和 T3。不是所有这些节点都需要在全量的 T 上工作，它们可以同时单独在一个分片上工作。如你所看到的，所节省的时间会是指数级的。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +与其他大部分的分片方法不同，这些方法依然需要节点在越来越複杂的硬件上运行（减少更多人参与网络的能力），NEAR 的技术允许节点保持足够小，可以在简单的云託管实例上运行。
```suggestion
相对而言，其他大部分的分片技术依然需要节点运行在越来越复杂的硬件上（以减少更多人参与网络的能力），而NEAR 的技术允许节点保持足够精简，甚至在简单的云实例上运行。
```       
        
> (reducing the ability of more people to participate in the network)               

这句话需要再考虑一下，我也没太好的翻译方法lol

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +提示：这不只是关于速度！
```suggestion
这不只是关于速度！
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +此外，这裡应该考虑另一个因素。当涉及到应用程式的可用性方面，速度是一个必要的因素。毕竟，如果应用程序根本不能用，用户为什么要使用它？开發人员需要有一定数量的用户在其应用程序达到临界质量前持续地使用该应用程式。
```suggestion
此外，这裡应该考虑另一个因素。当涉及到应用程序的可用性方面，速度是一个必要的因素。毕竟，如果应用程序根本不能用，用户为什么要使用它？毕竟开发者需要不断积累用户直到达到爆发。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +这就是为什么像NEAR的可扩展区块链平台对于区块链和智能合约的主流採用是很重要。
```suggestion
这就是为什么像NEAR这样的可扩展区块链平台对于区块链和智能合约的推广是很重要。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +NEAR始于 2018 年夏天，当时 Alex Skidanov 和 Illia Polosukhin 决定放弃他们之前的创业冒险，如果您好奇，可以在[这裡阅读更多相关资料](https://medium.com/nearprotocol/near-ai-near-protocol-8785c9d32096)。很快，随着 Misha 退出 MemSQL，团队在 8 月份的 3 天内从几人扩大到
```suggestion
NEAR始于 2018 年夏天，当时 Alex Skidanov 和 Illia Polosukhin 决定放弃他们之前的创业冒险（可以在[这裡阅读更多相关资料](https://medium.com/nearprotocol/near-ai-near-protocol-8785c9d32096)）。很快，随着 Misha 退出 MemSQL，团队在 8 月份的 3 天内从几人扩大到 9 人。最初的团队由 7 名工程师组成，Erik 负责业务营运，Sasha 负责市场营运。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +今天，NEAR Collective是分佈在全球的团队，由很多个体组织和贡献者组成，他们都是自發组织，目的是将NEAR这项技术实践出来。这不是一项商业业务或任何接近正式的事情。可以把它想像成为有一群人正在运行一个大型开源软件项目。
```suggestion
今天，NEAR Collective由分布在全球的诸多个人和组织构成，他们都是自发组织起来的，目的是将NEAR这项技术实践出来。这并不是一项商业活动，而更像是有一群人正在运行的一个大型开源软件项目。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +其中一个NEAR Collective的项目是为开源 NEAR 网络编写初始代码和参考实现，有点像在航天飞机上建造火箭助推器。他们的职责是做必要的研發工作来协助区块链进入轨道。由于NEAR的链的代码是[开源的](https://github.com/near)，所以任何人都可以作出贡献或运行它。
```suggestion
其中一个NEAR Collective的项目是为开源 NEAR 网络编写初始代码和参考实现，有点像在航天飞机上建造火箭助推器。他们的职责是做必要的研发工作来协助区块链步入正轨。由于NEAR的链的代码是[开源的](https://github.com/near)，所以任何人都可以作出贡献或运行它。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +要重点强调一下，像 NEAR 这样的网络是被设计为完全去中心化的。这表示NEAR最终完全独立运作，而且实际上无法被第三方删改、关闭或以其他方式扰乱…甚至最初构建它们的团队也不可以！因此，虽然这个Collective的成员在这裡开始构建参考实现，一旦网络开始运行，他们很快就对网络的运行变得微不足道。事实上，在NEAR一旦准备就绪，任何人都可以修改和运行 [NEAR 协议](https://lear
```suggestion
需要重点强调一下的是，像 NEAR 这样的网络是被设计为完全去中心化的。这表示NEAR最终完全独立运作，而且实际上无法被第三方删改、关闭或以其他方式扰乱…甚至最初构建它们的团队也不可以！因此，虽然这个Collective的成员在这里构建参考实现，但一旦网络开始运行，他们很快就会无法干预网络的运行。事实上，NEAR一旦准备就绪，任何人都可以修改和运行 [NEAR 协议](https://learnnear.club/integrating-with-near-protocol/)代码来启动他们自己的区块链，因为它都是开源的，而且任何修改都必须被运行它的独立验证者们以民主的方式接受才能够被正式提交。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +它的技术是支持加密货币。区块链是一种技术，可以将交易记录安全地存储在点对点的网络上，而不是将它们存储在单一位置。世界各地的独立服务器，称为节点，组成了一个运行区块链的网络。
```suggestion
near的技术基于加密货币。区块链是一种技术，可以将交易记录安全地存储在点对点的网络上，而不是将它们存储在单一位置。世界各地的独立服务器，称为节点，组成了一个运行区块链的网络。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +开發人员：在中心化的世界中，开發人员通常受云平台甚至政府的特别善待，以确保他们可以继续运行应用程式。在去中心化的世界裡，没有专横跋扈的中介。
```suggestion
开發人员：在中心化的世界中，开发人员只能依赖云服务商以确保他们应用程式能够正常运行。在去中心化的世界裡，没有专横跋扈的中介。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +共识协议是用于让系统中的多个参与者之间可以就单个价值达成一致共识。如果所有网络参与者都遵守共识协议进行合作，则新值可能会加到账本内并由节点进行验证。但是，在出现争议的情况下，网络可能会专注在安全性或活跃性。
```suggestion
共识协议是用于让系统中的多个参与者之间可以就单个价值达成一致共识。如果所有网络参与者都遵守共识协议进行合作，则新值可能会加到账本内并由节点进行验证。但是，在出现争议的情况下，网络会在安全性或活跃性中进行抉择以解决争议。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +在 NEAR 上实现的共识机制称为 Nightshade。 Nightshade 将系统模彷为单个区块链。每个区块中所有交易纪录的列表会被分成很多个物理块，每个分片只有一个块。所有块会累积到一个块。请注意所有块只能由维护该分片状态的节点进行验证。
```suggestion
在 NEAR 上实现的共识机制称为 Nightshade。 Nightshade 将系统模彷为单个区块链。每个区块中所有交易纪录会被分成很多个物理块，每个分片只有一个块。所有块会累积到一起组成一个大块。请注意所有块只能由维护该分片状态的节点进行验证。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +说到验证，NEAR 的一个关键组件是验证器。这些验证器负责维护协议内的共识。验证者是特定的节点，需要保持其服务器 100% 的在线时间，同时需要保持它的系统可以不断更新。
```suggestion
说到验证，NEAR 的一个关键组件是验证者。这些验证者负责维护协议内的共识。验证者是特定的节点，需要保持其服务器 100% 的在线时间，同时需要保持它的系统可以不断更新。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +	NEAR 会在每个新纪元决定谁是它的网络验证者，会根据参与者所持有的权益份额来选出网络验证者。
```suggestion
	NEAR 会在每个纪元开始的时候根据参与者所持有的权益份额来选出网络验证者。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +	潜在的验证者的其权益份额必须高于动态釐定的水平。
```suggestion
	其他潜在的验证者的权益份额必须高于动态决定的水平。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +共识基于巨大链的共识。意思是，区块生产者一旦發布了一新的个区块，他们就会收集所有验证者节点的签名。一个区块的权重是根据在该区块中的所有签名者的签名中当时累积的权益份额。一条链的权重是所有区块的权重的总和。另外，共识使用了一个确定性小工具，该工具引入了额外的”删除条件”以提高链的安全性。
```suggestion
整个链的共识由最大权重决定。也就是说，区块生产者一旦发布了一新的个区块，他们就会收集所有验证者节点的签名。一个区块的权重等于该块的所有验证者的权益之和。一条链的权重是所有区块的权重的总和。此外也用了其他的一些小技巧来提升区块链的安全性。
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +NEAR通证是 NEAR 生态系统的基本原生资产，而且NEAR的通证功能都能被所有账户启用。每个通证都是一种独特的数字资产与以太币相似，它可以用于：
```suggestion
NEAR通证是 NEAR 生态系统的基本原生资产，而且NEAR的通证功能都能被所有账户启用。每个通证都是一种独特的数字资产。与以太币相似，它可以用于：
```

2021-07-20 08:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +	透过参与通证抵押过程，将验证节点作为网络的一部分运行。
```suggestion
	透过参与通证抵押过程，运行一个验证节点。
```

2021-07-20 11:54 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +NEAR的主要任务是提供一个理想的平台，让应用程式运行在一个可访问的共享既安全的钱池，用家可以拥有自己的身份及数据资料。同时会将抗分割网络、无伺服器计算、分布式储存的特色结合成一种新型的平台。
好的，這個會修改，謝謝提醒

2021-07-20 12:59 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +比特币是第一代区块链的完美例子。该区块链的目的是成为一个简单直接的支付系统。从“互联网货币”开始，比特币已成为最受欢迎的资产类别之一。但是，当提及 BTC 时就会出现一个重要问题。BTC是不能应付複杂的交易，因为这些交易可能有多层元数据和逻辑。
BTC无法应对包含多層元数据和逻辑的复杂交易

2021-07-20 13:25 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +但区块链的發展一直与它的成长斗争，因为区块链一直存在严重的扩展性问题。例如: 比特币每秒的交易量为7笔，而以太坊每秒的交易量只有25笔。当同PayPal(每秒115笔)和Visa(每秒1700笔)比较，就相当不济。
是的，都是"發"字的問題，我會重新再看看

2021-07-20 13:45 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +公道来说，最近出现了一些第二层(Layer-two)解决方案，例如: Lightning Network Raiden, Plasma Protocal等，来应对以太坊与比特币的扩展性问题。这裡的想法是在底层区块链上创建一个附加层，让主要的协议也可以委派重複和繁琐的任务。
也可以這樣修改的

2021-07-20 14:19 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +正如我们目前看到的，随着越来越多的节点进入以太坊和比特币生态系统，整个共识和验证过程需要更多的时间。现在，分片将如何帮助区块链？
這裡的問句，是緊張下面的一句回應

2021-07-20 14:25 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +分片激活会發生什么？
原文有提及activation，你覺得在這裡用激活不太合適?

2021-07-20 14:55 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +与其他大部分的分片方法不同，这些方法依然需要节点在越来越複杂的硬件上运行（减少更多人参与网络的能力），NEAR 的技术允许节点保持足够小，可以在简单的云託管实例上运行。
硬件要求愈來愈，會讓入門的門檻提高，最終導致能夠參與節點營運的人減少了。
如果想翻譯得比較自然，可以用意思相近的表達方式。
例如翻譯為"最終導致能夠參與節點營運的人減少了"?

2021-07-20 15:10 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +此外，这裡应该考虑另一个因素。当涉及到应用程式的可用性方面，速度是一个必要的因素。毕竟，如果应用程序根本不能用，用户为什么要使用它？开發人员需要有一定数量的用户在其应用程序达到临界质量前持续地使用该应用程式。
應該是指在一個固定數量的用戶下進行持續測試之類，以了解應用程序在某固定數量的用戶下可以運作多久之類。目的是測試應用程序的極限。

2021-07-20 15:15 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +开發人员：在中心化的世界中，开發人员通常受云平台甚至政府的特别善待，以确保他们可以继续运行应用程式。在去中心化的世界裡，没有专横跋扈的中介。
按原文意思比較好，因為這裡想突出中心的問題

2021-07-20 15:31 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +共识基于巨大链的共识。意思是，区块生产者一旦發布了一新的个区块，他们就会收集所有验证者节点的签名。一个区块的权重是根据在该区块中的所有签名者的签名中当时累积的权益份额。一条链的权重是所有区块的权重的总和。另外，共识使用了一个确定性小工具，该工具引入了额外的”删除条件”以提高链的安全性。
"另外，共识使用了一个确定性小工具，该工具引入了额外的”删除条件”以提高链的安全性。"

确定性小工具是專有名詞，所以不建議修改。而後面的一句也很重要，不能刪。但如果你有更好的表達方式，可以給一下建議。

2021-07-21 02:40 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +为了解决这个问题，NEAR 使用了一种在数据库世界中已经非常流行的技术-分片。如果适当运用，它可以允许网络容量随着网络中节点数量的增加而扩展，因此没有理论上的网络容量限制。最好的部分？分片是一种针对第一层可扩展性的技术。
数据库领域中 👍 
后面一段话我觉得按你说的ok的，不过“最好的部分？”这一句有一点太生硬了，不如换成 “更好的是”

2021-07-21 02:41 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +分片激活会發生什么？
对的我觉得activation直接翻译过来不好理解，如果不翻译也可以完全明白这句话的意思

2021-07-21 02:45 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +此外，这裡应该考虑另一个因素。当涉及到应用程式的可用性方面，速度是一个必要的因素。毕竟，如果应用程序根本不能用，用户为什么要使用它？开發人员需要有一定数量的用户在其应用程序达到临界质量前持续地使用该应用程式。
我觉得这个地方好像理解有一点分歧，我的理解并不是要做压力测试之类的事情。
可以按照你的理解来，不过原本的那句话有点不通顺，改成你现在这样说会更好一点

2021-07-21 02:45 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +与其他大部分的分片方法不同，这些方法依然需要节点在越来越複杂的硬件上运行（减少更多人参与网络的能力），NEAR 的技术允许节点保持足够小，可以在简单的云託管实例上运行。
嗯这样说没问题

2021-07-21 02:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +	NEAR 会在每个纪元开始的时候根据参与者所持有的权益份额来选出网络验证者。
```suggestion
	NEAR 会在每个周期开始的时候根据参与者所持有的权益份额来选出网络验证者。
```
专有名词可以参考 https://github.com/near-x/learn-near-community/tree/master/cn/resources/glossary

2021-07-21 02:54 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +共识基于巨大链的共识。意思是，区块生产者一旦發布了一新的个区块，他们就会收集所有验证者节点的签名。一个区块的权重是根据在该区块中的所有签名者的签名中当时累积的权益份额。一条链的权重是所有区块的权重的总和。另外，共识使用了一个确定性小工具，该工具引入了额外的”删除条件”以提高链的安全性。
好的那这句话先不用做修改

2021-07-21 16:35 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +为了解决这个问题，NEAR 使用了一种在数据库世界中已经非常流行的技术-分片。如果适当运用，它可以允许网络容量随着网络中节点数量的增加而扩展，因此没有理论上的网络容量限制。最好的部分？分片是一种针对第一层可扩展性的技术。
對於原文的"The best part? Sharding is a layer-1 scalability technique."
我覺得是強調分片是NEAR的最好的部分, 你覺得呢?

2021-07-21 16:43 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +自从中本聪于 2008 年 10 月發布比特币白皮书以来，世界已经熟悉了会改变游戏规则的区块链技术。在过去的十年中，区块链经历了三个演进阶段。
好的

2021-07-21 16:47 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +	潜在的验证者的其权益份额必须高于动态釐定的水平。
潜在的验证 中的"潜在"已包含了"其他"的意思，所以我覺得可以不用額外加"其他"。

2021-07-21 16:52 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +	NEAR 会在每个纪元开始的时候根据参与者所持有的权益份额来选出网络验证者。
謝謝

2021-07-22 07:50 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +为了解决这个问题，NEAR 使用了一种在数据库世界中已经非常流行的技术-分片。如果适当运用，它可以允许网络容量随着网络中节点数量的增加而扩展，因此没有理论上的网络容量限制。最好的部分？分片是一种针对第一层可扩展性的技术。
嗯意思是没问题，不过我觉得the best part?是一个英文习语，翻译成中文的时候需要改成符合中文习惯的对应习语

2021-07-22 07:53 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +开發人员：在中心化的世界中，开發人员通常受云平台甚至政府的特别善待，以确保他们可以继续运行应用程式。在去中心化的世界裡，没有专横跋扈的中介。
意思是对的但是这句话不太符合中文习惯，因为“善待”在中文中的意思是“受到特殊照顾”，原文其实并没有这个意思。只是想表达依赖于中心化的云服务上不出问题而已

2021-07-23 08:24 UTC, danielwpz commented on cn/resources/guides/what-is-near-protocol_1.md
> +	潜在的验证者的其权益份额必须高于动态釐定的水平。
嗯ok

2021-07-24 03:47 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_1.md
> +开發人员：在中心化的世界中，开發人员通常受云平台甚至政府的特别善待，以确保他们可以继续运行应用程式。在去中心化的世界裡，没有专横跋扈的中介。
謝謝指教，我也重新去看一遍，的確是沒有“善待”的意思。

2021-07-28 10:25 UTC, merged

2021-08-17 01:41 UTC, shepf commented
翻译质量评价: 优秀

2021-08-17 02:03 UTC, wongxf commented
翻译质量评价: 优秀