what-is-near-protocol_2
near-x/learn-near-community pull request #22
Opened 2021-07-12 07:03 UTC by marco-sundsk

waiting for review.

2021-07-14 03:30 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_2.md
> +与其他可编程网络类似，NEAR通过交易费，也叫Gas费补偿这些人。
```suggestion
与其他可编程的区块链类似，NEAR通过交易费，也叫Gas费补来偿验证者。
```

2021-07-14 03:39 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_2.md
> +如果你熟悉web2上的云服务提供商（亚马逊云，谷歌云等），区块链与其的最大不同是，用户在访问应用的时候直接支付费用，而不是开发者预付所有的基础设施费用。这带来了新的可能性，例如，应用本身规避了长期的入不敷出的资金风险。但这也带来了一些用户可用性上的问题。为了解决这个问题，NEAR也提供了让开发者支付用户使用开销的能力，让使用体验更靠近web2。
```suggestion
如果你熟悉web2上的云服务提供商（亚马逊云，谷歌云等），区块链与其的最大不同是，用户在访问应用的时候直接支付费用，而不是开发者预付所有的基础设施费用。这带来了新的可能性，例如，应用本身规避了长期的入不敷出的资金风险。但这也带来了一些用户可用性上的阻碍。为了解决这个问题，NEAR也提供了让开发者支付用户使用开销的能力，让使用体验更靠近web2。
```

2021-07-14 03:42 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_2.md
> +2. Gas价格: gas单位乘以gas价格得到具体的向用户收取的费用。这个价格会在每个块时根据网络需求自动重新计算（如果前面块的gas数量超过半满，则价格上升，否则价格下降，每个块的价格变动不会超过1%）。最低的价格由网络配置决定，当前是1亿个yoctoNEAR。
```suggestion
2. Gas价格: gas单位乘以gas价格得到具体的向用户收取的费用。这个价格会在每个区块时根据网络需求自动重新计算（如果前面块的gas数量超过半满，则价格上升，否则价格下降，每个区块的价格变动不会超过1%）。最低的价格由网络配置决定，当前是1亿个yoctoNEAR。
```

2021-07-14 03:52 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_2.md
> +这里的1ms是一个粗略但有益的近似，也是目前NEAR中单位gas的设计目标。Gas单位不仅封装了计算/CPU时间，也包含带宽/网络时间和存储/IO时间。通过治理机制，将来系统参数是可以调整的，可以改变TGas与1毫秒之间的对应关系。即便如此，上面的内容也是一个不错的开始，让你了解单位gas的意义以及它是怎么得来的。
```suggestion
这里的1ms是一个粗略但有用的近似值，也是目前NEAR中对gas单位设定的目标。Gas单位不仅封装了计算/CPU时间，也包含带宽/网络时间和存储/IO时间。通过治理机制，将来系统参数是可以调整的，可以改变TGas与1毫秒之间的对应关系。即便如此，上面的内容也是一个不错的开始，让你了解单位gas的意义以及它是怎么得来的。 
```

2021-07-14 04:09 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_2.md
> +POS模型的关键点在于，社区是如何通过抵押而给予验证人支持的。验证人运营节点以支撑起整个网络，因此获得每年5%固定通胀率的奖励，具体是每个周期（约12个小时）创建出一批新的通证。
```suggestion
POS模型的关键点在于，社区是如何通过抵押而给予验证人支持的。验证人运营节点以支撑起整个网络，因此获得每年5%固定通胀率的NEAR通证奖励，具体是每个周期（约12个小时）创建出一批新的通证。
```

2021-07-14 04:22 UTC, MartinYeung5 commented on cn/resources/guides/what-is-near-protocol_2.md
> +You will need to confirm two transactions, one to select the validator, and another to deposit and stake with the validator.
```suggestion
你需要确认两次交易，第一是选择验证者，第二是向验证者存入权益的数量
```

2021-07-29 03:52 UTC, think-in-universe requested changes

2021-07-29 03:52 UTC, think-in-universe commented on cn/resources/guides/what-is-near-protocol_2.md
> +你可以通过参与[开发赏金任务](https://github.com/near/bounties)获得$NEAR, 运营一个帮助大家在NEAR上开发的[技术社区](https://near.org/guilds)，赢取NEAR骇客松比赛，或成为社区里的积极分子。如果你能吸引别人投NEAR给你抵押，你就可以成为一个验证人来赚取$NEAR。
```suggestion
你可以通过参与[开发赏金任务](https://github.com/near/bounties)获得$NEAR, 运营一个帮助大家在NEAR上开发的[技术社区](https://near.org/guilds)，赢取NEAR黑客松比赛，或成为社区里的积极分子。如果你能吸引别人投NEAR给你抵押，你就可以成为一个验证人来赚取$NEAR。
```

2021-07-29 03:52 UTC, think-in-universe commented on cn/resources/guides/what-is-near-protocol_2.md
> +如果你的朋友向创建一个NEAR账户，可以给他们发送一个[NEAR空投](https://near.org/blog/send-near-to-anyone-with-near-drops/)。
```suggestion
如果你的朋友想创建一个NEAR账户，可以给他们发送一个[NEAR空投](https://near.org/blog/send-near-to-anyone-with-near-drops/)。
```

2021-07-29 03:52 UTC, think-in-universe commented on cn/resources/guides/what-is-near-protocol_2.md
> +注意：测试网和装的gas价格可能不同。在直接使用下面的数字之前，要检查一下gas价格。
```suggestion
注意：测试网和主网的gas价格可能不同。在直接使用下面的数字之前，要检查一下gas价格。
```

2021-07-29 03:52 UTC, think-in-universe commented on cn/resources/guides/what-is-near-protocol_2.md
> +1 毫秒的计算时
```suggestion
1 毫秒的计算时间
```

2021-07-29 03:52 UTC, think-in-universe commented on cn/resources/guides/what-is-near-protocol_2.md
> +1 纳秒的计算时
```suggestion
1 纳秒的计算时间
```

2021-07-29 03:53 UTC, think-in-universe commented
several typos that require change

2021-07-29 04:27 UTC, merged

2021-08-17 01:42 UTC, shepf commented
翻译质量评价: 优秀

2021-08-19 02:48 UTC, wongxf commented
翻译质量评价: 优秀

2021-08-19 02:55 UTC, think-in-universe commented
翻译质量评价: 优秀

2021-08-19 04:29 UTC, MartinYeung5 commented
翻译质量评价: 优秀