Near account express guide
near-x/learn-near-community pull request #3
Opened 2021-06-19 14:11 UTC by shepf

fix your commit

2021-06-20 04:03 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +8. 对于Fullaccess访问级别，所有8种类型的操作可用：CreateAccOrction（创建一个帐户），部署（部署合约），功能调用（调用合约方法），
需要修复大小写以及拼写错误

2021-06-20 04:04 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +3. 在NEAR 有3种类型的keys。 访问密钥用于从帐户签名交易，验证器密钥允许与网络验证相关的操作，节点密钥（网络节点）允许网络上节点之间的低级通信。
这一段容易误导读者，一般只需用到 Full Access Key 和 Function Call Key

2021-06-20 04:06 UTC, think-in-universe requested changes

2021-06-20 04:06 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +7. 所有密钥在一个帐户中是唯一的，但公钥可以分配给具有不同访问级别的不同帐户。 访问级别确定可以使用此密钥执行帐户中的操作。
`访问级别确定可以使用此密钥执行帐户中的操作` 不通顺

2021-06-20 04:15 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +3. 在NEAR 有3种类型的keys。 访问密钥用于从帐户签名交易，验证器密钥允许与网络验证相关的操作，节点密钥（网络节点）允许网络上节点之间的低级通信。
可以添加一些链接，方便读者进一步了解这3种 key；并强调接下来主要讨论的是 Access Key

2021-06-20 05:18 UTC, shepf commented on cn/resources/guides/near-account-express-guide.md
> +8. 对于Fullaccess访问级别，所有8种类型的操作可用：CreateAccOrction（创建一个帐户），部署（部署合约），功能调用（调用合约方法），
8. 对于 FullAccess 访问级别，所有8种类型的操作可用：CreateAccountAction（创建一个帐户），DeployContractAction（部署合约），FunctionCallAction（调用合约方法），
   TransferAction（将代币发送到另一个帐户），StakeAction（抵押tokens）， AddKeyAction（将一个秘钥添加到帐户），DeleteKeyAction（删除帐户密钥），
   DeleteAccountAction（删除帐户）。

2021-06-20 05:21 UTC, shepf commented on cn/resources/guides/near-account-express-guide.md
> +7. 所有密钥在一个帐户中是唯一的，但公钥可以分配给具有不同访问级别的不同帐户。 访问级别确定可以使用此密钥执行帐户中的操作。
7. 所有密钥在一个帐户中是唯一的，但公钥可以分配给具有不同访问级别的不同帐户。 访问级别决定了可以使用此密钥执行帐户中的哪些操作。

2021-06-21 02:23 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +3. 在NEAR 有3种类型的keys。[Access keys](https://learnnear.club/docs/concepts/new-to-near/)用于从帐户交易签名，**validator keys**允许与网络验证相关的操作，**node keys**（网络节点）允许网络上节点之间的底层通信。
原文链接有误，不必拘泥于和原文完全一致，可以参考：https://docs.near.org/docs/develop/node/intro/types-of-node

2021-06-21 02:24 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +3. 在NEAR 有3种类型的keys。[Access keys](https://learnnear.club/docs/concepts/new-to-near/)用于从帐户交易签名，**validator keys**允许与网络验证相关的操作，**node keys**（网络节点）允许网络上节点之间的底层通信。
可以给英文原文加一些 comment，帮助其改进

2021-06-21 06:04 UTC, shepf commented on cn/resources/guides/near-account-express-guide.md
> +3. 在NEAR 有3种类型的keys。[Access keys](https://learnnear.club/docs/concepts/new-to-near/)用于从帐户交易签名，**validator keys**允许与网络验证相关的操作，**node keys**（网络节点）允许网络上节点之间的底层通信。
3. 在NEAR 有3种类型的keys。**access keys**用于帐户交易签名，**validator keys**允许与网络验证相关的操作，**node keys**（网络节点）允许网络上节点之间的底层通信。

2021-06-21 16:41 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +6. 除了可见的帐户（name.near类型），NEAR 生态系统还支持在 near-cli的帮助下建立不可见账户（它们看起来与比特币和以太坊地址相似）。
implicit account 翻译成 `不可见账户` 也不太准确，翻译成 `隐性账户` 更好一些

2021-06-21 22:14 UTC, shepf commented on cn/resources/guides/near-account-express-guide.md
> +6. 除了可见的帐户（name.near类型），NEAR 生态系统还支持在 near-cli的帮助下建立不可见账户（它们看起来与比特币和以太坊地址相似）。
good

2021-06-22 02:30 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +3. NEAR钱包 (https://wallet.near.org/) （NEAR协议钱包），NEAR水龙头(https://faucet.paras.id/)（Ethereum и Metamask用户的水龙头）
每一小节之内应该不用添加额外的分行。每一节和下一节之间应该也不用分行。下同。

2021-06-23 16:34 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +   contract_2.maria.near等。
这里的空行也要改。。。下面还有

2021-06-23 16:35 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +   您可以在此处找到详细的[英文指南](https://learnnear.club/doc/roles/integrator/implicit-accounts/)
换行也要改

2021-06-23 16:35 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +   TransferAction（将代币发送到另一个帐户），StakeAction（抵押tokens）， AddKeyAction（将一个秘钥添加到帐户），DeleteKeyAction（删除帐户密钥），
换行也要改

2021-06-24 13:33 UTC, think-in-universe requested changes

2021-06-24 15:00 UTC, think-in-universe requested changes

2021-06-24 15:00 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +4. 在NEAR您可以创建一个帐户并在 https://nearnames.com 服务的帮助下将其作为礼物发送给朋友或订阅者。
```suggestion
4. 通过 https://nearnames.com 服务，您可以创建一个 NEAR 帐户并的作为礼物发送给朋友或订阅者。
```

2021-06-24 15:00 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +6. 除了显式的帐户（name.near类型），NEAR 生态系统还支持在 near-cli的帮助下建立隐式账户（它们看起来与比特币和以太坊地址相似）。 您可以在此处找到详细的[英文指南](https://learnnear.club/doc/roles/integrator/implicit-accounts/)
```suggestion
6. 除了显式帐户（name.near类型），NEAR 生态系统还支持通过 near-cli 创建隐式账户（它们看起来与比特币和以太坊地址相似）。 您可以在此处找到详细的[英文指南](https://docs.near.org/docs/roles/integrator/implicit-accounts)
```

2021-06-24 15:00 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +8. 在NEAR生态系统中有开发者帐户（https://docs.norg/docs/concepts/accounts#dev-accounts）。 他们的专用于测试和调试智能合约。
```suggestion
8. 在NEAR生态系统中有开发者帐户（https://docs.near.org/docs/concepts/account#dev-accounts）。 他们的专用于测试和调试智能合约。
```

2021-06-24 15:00 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +2. NEAR 用户使用公钥进行身份识别和私钥进行签名交易（在交易创建期间确认帐户所有权）。
```suggestion
2. NEAR 用户使用公钥进行身份识别，用私钥进行签名交易（在交易创建期间确认帐户所有权）。
```

2021-06-24 15:00 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +3. 在NEAR 有3种类型的keys。**access keys**用于帐户交易签名，**validator keys**允许与网络验证相关的操作，**node keys**（网络节点）允许网络上节点之间的底层通信。
```suggestion
在NEAR 有3种类型的密钥：**Access Keys**用于帐户交易签名，**Validator Keys**允许与网络验证相关的操作，**Node Keys**（网络节点）允许网络上节点之间的底层通信。更多资料介绍可以参考[这里](https://docs.near.org/docs/develop/node/intro/types-of-node)
```

2021-06-24 15:00 UTC, think-in-universe commented on cn/resources/guides/near-account-express-guide.md
> +4. 密钥可以存储在3种不同的存储中：**BrowserLocalStorageKeyStore** - 未加密的本地浏览器存储，用于使用浏览器中的应用程序；**InMemoryKeyStore** - 内存存储，用于临时方案或在本地程序指定特定的密钥； **UnencryptedFileSystemKeyStore** - 在使用near-cli或本地程序时，使用的文件系统中的未加密存储。
```suggestion
4. 密钥可以存储在3种不同的存储中：**BrowserLocalStorageKeyStore** - 未加密的本地浏览器存储，用于使用浏览器中的应用程序；**InMemoryKeyStore** - 内存存储，用于临时方案或在本地程序指定特定的密钥； **UnencryptedFileSystemKeyStore** - 用于 near-cli或本地程序，是位于文件系统中的未加密存储。
```

2021-06-25 14:39 UTC, think-in-universe approved these changes

2021-06-25 14:39 UTC, merged

2021-08-10 06:35 UTC, think-in-universe commented
翻译质量评价: 一般