Near protocol and solana
near-x/learn-near-community pull request #5
Opened 2021-06-21 15:23 UTC by shepf

2021-07-03 03:54 UTC, tigerjibo reviewed
review

2021-07-03 03:54 UTC, tigerjibo commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +
```suggestion
```

2021-07-03 03:54 UTC, tigerjibo commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +今天，让我们来看看世界上最有前途的两个智能合约平台—— Near Protocol 和 Solana。虽然 Ethereum 仍然主导着这个市场，
今天，让我们来认识下世界上最有前途的两个智能合约平台- Near Protocol和Solana。尽管目前Ethereum依旧主导这个市场

2021-07-03 03:54 UTC, tigerjibo commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +解决比特币和以太网存在的问题。该项目吸引了来自 Multicoin Capital、 Foundation Capital、 SLOW Capital、 CMCC Global、 Abstract Ventures 等公司的投资。
创立Solana主要是解决比特币和以太坊目前存在的问题

2021-07-03 06:09 UTC, tigerjibo reviewed
all of review

2021-07-03 06:09 UTC, tigerjibo commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +这一共识是基于最重链共识。这意味着，一旦块生成器发布了一个块，它们将收集验证器节点的签名。然后，块的重量是该块中包含签名的所有签名者的累积。链条的重量是各块重量之和。此外，协商一致意见使用了一个终结性小工具，为更高的链安全性引入了额外的条件。
```suggestion
这一共识是基于最重链共识。这意味着，一旦块生成器发布了一个块，它们将收集验证器节点的签名。然后，块的权重是该块中包含签名的所有签名者的累积。该链的权重是各块权重之和。此外，协商一致意见使用了一个终结性小工具，为更高的链安全性引入了额外的条件。
```

2021-07-03 06:09 UTC, tigerjibo commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +
```suggestion
Doomslug”是哪个协议的块生成机制?  

-Near协议
-Solana
```

2021-07-03 06:09 UTC, tigerjibo commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +合同解释
```suggestion
合约解释
```

2021-07-03 06:09 UTC, tigerjibo commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +Solana 和 NEAR 协议都是卓越的智能合约平台，已经建立了高度活跃的社区。他们都带来了特殊的功能，帮助解决去中心化最大的问题，速度。
```suggestion
Solana 和 NEAR 协议都是卓越的智能合约平台，已经建立了高度活跃的社区。他们都带来了特殊的功能，帮助解决去中心化最大的问题-速度。
```

2021-07-03 08:00 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +今天，让我们来看看世界上最有前途的两个智能合约平台—— Near Protocol 和 Solana。虽然 Ethereum 仍然主导着这个市场，
good suggestion

2021-07-03 08:10 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +说到验证，NEAR 的一个关键组件是验证器。这些验证者负责在协议中保持共识。验证器是专门的节点，它需要100% 的时间保持服务器在线，同时保持系统不断更新。
这个群里面 讨论过，用验证者

2021-07-05 13:31 UTC, tigerjibo approved these changes
review finished

2021-07-07 14:41 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 在网络中计时的交易或事件将被指定为唯一的散列计数，可以进行公开验证
在网络中的所有交易及活动都可被测量，同时每个测量会产生一个独一无二的哈希(Hash)，可以被公开验证。

2021-07-07 14:41 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 计数允许网络准确地知道交易或事件发生的时间
每个测量都允许网络准确地知道交易或事件的发生时间

2021-07-07 14:41 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +由于使用了 PoH，当使用 gpu 运行时，Solana 网络每秒支持50,000个交易。
基于历史证明( PoH)，当使用 GPU 运行时，Solana 网络每秒支持50,000个交易。

2021-07-07 14:43 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 每秒50,000次交易和0.4秒的阻塞时间
nice

2021-07-07 14:49 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +Solana使用历史证明算法，通过创造历史记录来证明某一事件发生在某一特定时刻。以下要点需要记住:
Solana使用历史证明算法，通过创造历史记录来证明某一事件发生在某一特定时刻。以下几点需要记住:

我把要点改成 几点，感觉差不多

2021-07-07 14:50 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 在网络中计时的交易或事件将被指定为唯一的散列计数，可以进行公开验证
测量 感觉 怪怪的，现在还不知道，怎么改

2021-07-07 14:50 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 计数允许网络准确地知道交易或事件发生的时间
测量？

2021-07-07 15:43 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 在网络中计时的交易或事件将被指定为唯一的散列计数，可以进行公开验证
因為clock的動詞有測量的意思，當完成一次測量就會生成一個hash，而原文中的a unique hash a count，我就理解為每個count就會有一個Hash，而一個count就等於一次測量，所以就把count翻譯為測量。
如果我的理解有什麼問題，可以糾正我。

2021-07-08 02:39 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 它们有助于验证用户提交程序的不可信输出
它们有助于验证未受信任的输出及用户提交的程式

2021-07-08 02:48 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 维护用户进行的任何交易或事件的记录
维护用户留下的任何交易或事件的记录

2021-07-08 03:03 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 它跟踪哪些计算机做了有意义的工作来保持网络运行
它保留着有关哪些计算机做了有意义的工作的纪录来维持网络运行

2021-07-08 03:04 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 它跟踪真实世界资产的占有情况
它保留着有关真实世界中资产的拥有权的纪录

2021-07-08 03:12 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +Solana 中的智能合约是用 Rust 或 c 编写的，并编译成 BPF/字节码(BPF)。由于有更多的工具可用，建议您在 Rust 中编写代码。初学者应该使用 Anchor 框架编写程序代码，该框架可以简化执行。
Solana 中的智能合约是用 Rust 或 c 编写的，并编译成伯克利包过滤器(BPF)字节码。由于有更多的工具可用，建议您在 Rust 中编写代码。初学者应该使用 Anchor 框架编写程序代码，该框架可以简化执行过程。

2021-07-08 03:49 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 在网络中计时的交易或事件将被指定为唯一的散列计数，可以进行公开验证
总感觉很别扭

2021-07-08 04:15 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +Solana 当前的编程模型可能会迫使您将应用程序逻辑移出链或修改功能，使其效率低下并受到固定帐户大小的限制。
Solana目前的编程模型受制于固定的帐户大小，可能会迫使你将应用程序的逻辑部份转移到链下或修改功能以调低效率。

2021-07-08 04:56 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +并在2019年引入了名为“Doomlug”的块生成机制。Doomslug允许实践（practical）或 “Doomslug”最终性(Finality)，确保在秒内得到最终性(Finality)。
它还引入了在 2019 年提出的名为"Doomslug"的区块生成机制。 Doomslug 允许实用确定性或"Doomslug"确定性，确保区块在几秒钟内获得确定性。

2021-07-08 05:04 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +该协议于2018年夏天发布，旨在通过提供更高的速度、更高的吞吐量以及更好的与其他链的兼容性，为分散式应用程序创建完美的环境。NEAR 有一个独特的分片技术，
NEAR 协议诞生于 2018 年夏天。 该协议旨在为去中心化应用程式创造完美的环境，它可以提供更高速、更高吞吐量以及与其他链有更好的兼容性。NEAR 有一个独特的分片技术，

2021-07-08 05:06 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +该协议于2018年夏天发布，旨在通过提供更高的速度、更高的吞吐量以及更好的与其他链的兼容性，为分散式应用程序创建完美的环境。NEAR 有一个独特的分片技术，
统一专业用语: decentralized applications = 去中心化应用程式

2021-07-08 05:09 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +NEAR 协议是由 NEAR Collective 开发的，这是一个由开发人员和研究人员合作构建项目的社区。以下是NEAR 的一些关键特性:
NEAR 协议是由 NEAR社区贡献者(the NEAR collective) 开发的，这是一个由开发人员和研究人员合作构建项目的社区。以下是NEAR 的一些关键特性:

2021-07-08 05:12 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +NEAR 协议是由 NEAR Collective 开发的，这是一个由开发人员和研究人员合作构建项目的社区。以下是NEAR 的一些关键特性:
我在网上有查看了一些资料, the NEAR collective 是一个专称，所以从它所包含的意思进行翻译比较好。而且看到有人把the NEAR collective称为NEAR 社区贡献者，我觉得是挺合适的，加上在原文的解释也包含community，让人觉得比较像一个社区。
不知道大家觉得怎样?
如果不知道怎样改，可以保留原文的英文

2021-07-08 05:12 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* NEAR 是一个分片系统，它支持无限的可伸缩性
NEAR 是一个分片系统，允许无限的可扩展性。

2021-07-08 05:13 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* NEAR 是一种易于使用的协议，它允许开发人员轻松快速地构建应用程序
NEAR 是一种易于使用的协议，允许开发人员轻松快速地构建应用程式。

2021-07-08 05:16 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +NEAR Collective包括个人组织和其他贡献者，这些组织和贡献者不断致力于改进 NEAR 协议。该小组负责编写 NEAR 网络的初始代码和实现等项目。NEAR 完全去中心化，独立运行，不能被关闭或操纵，即使是那些构建它的人。
NEAR Collective由不断致力于改进 NEAR 协议的个人组织和其他贡献者组成。 该Collective致力于为 NEAR 网络编写初始代码和進行實踐等项目。 NEAR 是完全去中心化的，独立运行，不能被关闭或操纵，

2021-07-08 05:39 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +在 NEAR 上实现的共识制称为Nightshade。Nightshade模型的系统作为一个单一的区块链。每个块中的所有交易的列表被分割为物理块，每个碎片一个块。所有块都聚集到一个块中。注意，块只能由维护碎片状态的节点进行验证。
在 NEAR 上实现的共识制称为Nightshade。Nightshade 将系统视为单个区块链。每个区块中所有交易的列表会被拆分为多个碎块，每个碎块中会有一个分片。所有碎块可以组成一个区块，碎块只可以被维持它的分片状态的节点进行验证。

2021-07-08 05:43 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +说到验证，NEAR 的一个关键组件是验证器。这些验证者负责在协议中保持共识。验证器是专门的节点，它需要100% 的时间保持服务器在线，同时保持系统不断更新。
说到验证，NEAR 的一个关键组件是验证者。这些验证者负责维持在协议内的共识。验证者是专门的节点，它需要保持服务器一直在线，同时保持系统在最新状态。

2021-07-08 05:45 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 每个epoch都会确定它的网络验证器，并根据它们的抵押选择它们
每个时期都会根据他们的权益选择验证者。

2021-07-08 05:46 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +关于网络验证器，您必须牢记以下几点。
关于网络验证者，您必须牢记以下几点。

2021-07-08 05:47 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 已经被选举出来的验证者通过自动重新抵押他们的代币和获取奖励
验证者可以通过重新抵押他们的通证和奖励来再次参加。

2021-07-08 05:57 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 潜在的验证者必须将他们的抵押保持在一个动态确定的水平之上
潜在的验证者的其权益份额必须高于动态釐定的水平。

2021-07-08 05:58 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 验证器可以使用两种方法来增强自己的股权——自己购买代币或通过抵押委托借用
验证者可以使用两种方法来加强他们的权益份额-自己购买通证或通过其他人的权益委託而借入通证。

2021-07-08 06:00 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 你得到的回报与你的抵押成正比-抵押越多，回报越多
您所获得的奖励与您的权益份额成正比。您的权益份额越多，您的奖励就越多。

2021-07-08 06:04 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +这一共识是基于最重链共识。这意味着，一旦块生成器发布了一个块，它们将收集验证器节点的签名。然后，块的权重是该块中包含签名的所有签名者的累积。该链的权重是各块权重之和。此外，协商一致意见使用了一个终结性小工具，为更高的链安全性引入了额外的条件。
共识基于巨大链的共识。意思是，区块生产者一旦發布了一新的个区块，他们就会收集所有验证者节点的签名。一个区块的权重是根据在该区块中的所有签名者的签名中当时累积的权益份额。一条链的权重是所有区块的权重的总和。另外，共识使用了一个确定性小工具，该工具引入了额外的”删除条件”以提高链的安全性。

2021-07-08 06:09 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +这一共识是基于最重链共识。这意味着，一旦块生成器发布了一个块，它们将收集验证器节点的签名。然后，块的权重是该块中包含签名的所有签名者的累积。该链的权重是各块权重之和。此外，协商一致意见使用了一个终结性小工具，为更高的链安全性引入了额外的条件。
统一专业用语:
Block = 区块
Validator = 验证者
finality gadget = 确定性小工具
Stake = 权益

2021-07-08 06:11 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +Doomslug”是哪个协议的块生成机制?
Doomslug 是哪个协议的区块生成机制?

2021-07-08 06:13 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +Aurora 也已经启动了 NEAR 协议，提供了一个以太坊 Layer-2体验，Aurora 改进 NEAR 的一些方法是:
Aurora 也在NEAR 协议上推出，提供以太坊第 2 层体验，Aurora 改进 NEAR 的一些方法是:

2021-07-08 06:17 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 块的finality时间为2秒
```suggestion
* 区块的确定性时间为2秒
```

2021-07-08 06:19 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 维护用户进行的任何交易或事件的记录
进行的 什么 的记录 ，感觉可以吧

2021-07-08 06:22 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 在网络中计时的交易或事件将被指定为唯一的散列计数，可以进行公开验证
你对原文的意思有什麽理解?

2021-07-08 07:11 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 潜在的验证者必须将他们的抵押保持在一个动态确定的水平之上
虽然 抵押 和权益挂钩，但是这里抵押还是比较明确一些

2021-07-08 07:11 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 验证器可以使用两种方法来增强自己的股权——自己购买代币或通过抵押委托借用
```suggestion
* 验证者可以使用两种方法来加强他们的权益份额-自己购买通证或通过借用其他人的抵押委托。
```

2021-07-08 07:11 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 你得到的回报与你的抵押成正比-抵押越多，回报越多
```suggestion
* 你得到的回报与你的抵押成正比-抵押越多，奖励越多
```

2021-07-08 07:11 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +这一共识是基于最重链共识。这意味着，一旦块生成器发布了一个块，它们将收集验证器节点的签名。然后，块的权重是该块中包含签名的所有签名者的累积。该链的权重是各块权重之和。此外，协商一致意见使用了一个终结性小工具，为更高的链安全性引入了额外的条件。
```suggestion
这一共识是基于最重权重链共识。这意味着，一旦块生成器发布了一个块，它们将收集验证者节点的签名。然后，块的权重是该块中包含签名的所有签名者的累积。该链的权重是各块权重之和。另外，共识使用了一个确定性小工具，该工具引入了额外的”删除条件”以提高链的安全性。
```

2021-07-08 07:11 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +Doomslug”是哪个协议的块生成机制?
```suggestion
Doomslug 是哪个协议的区块生成机制?
```

2021-07-08 07:11 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +Aurora 也已经启动了 NEAR 协议，提供了一个以太坊 Layer-2体验，Aurora 改进 NEAR 的一些方法是:
```suggestion
Aurora 也在NEAR 协议上推出，提供以太坊第 2 层体验，Aurora 改进 NEAR 的一些方法是:
```

2021-07-08 07:11 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 块的finality时间为2秒
```suggestion
* 区块的确定性时间为2秒
```

2021-07-08 07:16 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +这一共识是基于最重链共识。这意味着，一旦块生成器发布了一个块，它们将收集验证器节点的签名。然后，块的权重是该块中包含签名的所有签名者的累积。该链的权重是各块权重之和。此外，协商一致意见使用了一个终结性小工具，为更高的链安全性引入了额外的条件。
根据建议，做了部分修订

2021-07-08 08:33 UTC, shepf commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 已经被选举出来的验证者通过自动重新抵押他们的代币和获取奖励
```suggestion
* 已获选的验证者可以通过重新抵押他们的通证和累积的奖励来再次参加。
```

2021-07-12 05:02 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 计数允许网络准确地知道交易或事件发生的时间
因為每個count都表示一組數據紀錄，類似測量器/紀錄器在某特殊時刻紀錄(當時)的相關資料。
或者用每個紀錄?

2021-07-22 09:31 UTC, danielwpz requested changes

2021-07-22 09:31 UTC, danielwpz commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +[Solana](https://solana.com/) 成立于2017年，创始人是曾在 DropBox 工作过的 Yakovenko, 以及 Eric Williams and CTO Greg Fritzgerald，
```suggestion
[Solana](https://solana.com/) 成立于2017年，创始人是曾在 DropBox 工作过的 Yakovenko, Eric Williams 以及作为CTO的 Greg Fritzgerald，
```

2021-07-22 09:31 UTC, danielwpz commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 合约的状态位于 ContentRecord 结构中。使用 #[account]  注解，以表明它代表的数据布局的帐户
```suggestion
* 合约的状态位于 ContentRecord 结构中。使用 #[account]  注解，以表明它代表了账户的数据布局
```

2021-07-22 09:31 UTC, danielwpz commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 潜在的验证者必须将他们的抵押保持在一个动态确定的水平之上
```suggestion
* 潜在的验证者必须保证他们的抵押保持在一个动态确定的值之上
```

2021-07-22 09:31 UTC, danielwpz commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 该合约由 ContentTracker 中的 #[near_bindgen] 定义，它类似于 Solidity 中的构造函数，并在部署契约时调用
```suggestion
* 该合约由 ContentTracker 中的 #[near_bindgen] 定义，它类似于 Solidity 中的构造函数，并在部署合约时调用
```

2021-07-22 09:31 UTC, danielwpz commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 数据结构 LookupMap < String，ContentRecord > 处理键值查找，它访问存储，这等同于 soliity“ mapping”
```suggestion
* 数据结构 LookupMap < String，ContentRecord > 处理键值查找，这等同于 soliity的“mapping”
```

2021-07-23 08:23 UTC, danielwpz approved these changes
lgtm

2021-07-23 08:31 UTC, merged

2021-08-14 03:24 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 每个epoch都会确定它的网络验证者，并根据它们的抵押选择它们
每个周期都会确定它的网络验证者，并根据它们的抵押选择它们

2021-08-14 03:25 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 每个epoch都会确定它的网络验证者，并根据它们的抵押选择它们
每个周期都会确定它的网络验证者，并根据它们的抵押选择它们

2021-08-14 03:26 UTC, MartinYeung5 commented on cn/resources/guides/NEAR_Protocol_and_Solana.md
> +* 每个epoch都会确定它的网络验证者，并根据它们的抵押选择它们
@shepf

2021-08-14 03:38 UTC, MartinYeung5 commented
翻译质量评价: 一般
我发现有些地方仍存在问题，例如: scalability在同一文章被翻译成不同词语，我觉得统一比较好，除非是有特殊意思。还有一些字的翻译可以参看https://github.com/near-x/learn-near-community/tree/master/cn/resources/glossary，统一翻译。
建议再重新看一遍。