how-the-rainbow-bridge-works
near-x/learn-near-community pull request #7
Opened 2021-06-30 04:42 UTC by marco-sundsk

Completed, ready for review.

2021-07-01 12:18 UTC, wongxf commented
https://github.com/near-x/learn-near-community/pull/7/commits/e48fa5b516e14edc4dd7d3a0e3b429c0c1b4881b

2021-07-01 12:45 UTC, wongxf commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +The NEAR Protocol created the [Rainbow Bridge](https://ethereum.bridgetonear.org/)—something that’s both unique and valuable in the crypto space, a fully “trustless” bridge for transferring tokens be
```suggestion
NEAR 协议创建了 [彩虹桥](https://ethereum.bridgetonear.org/)——它在加密领域既独特又有价值，是一个完全“去信任”的桥梁，用于在以太坊和 NEAR 之间传输代币
```

2021-07-02 14:24 UTC, MartinYeung5 commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +NEAR协议构建了[彩虹桥](https://ethereum.bridgetonear.org/)—一个在密码学领域独特且高价值的全去中心化桥，可以在以太坊与NEAR之间，以及最终与极光(Aurora)之间转移通证。已有一些技术文档描述这个桥，而本文希望能让任何一个对密码学有基本认识的人能了解这个桥的工作机制。
個人認為可以用 完全去信任的橋 or 完全無需信任的橋 來取代 "全去中心化橋"，因為可以更準備地表達原文所強調的意思。

2021-07-03 03:57 UTC, MartinYeung5 commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +假设我要从[以太坊转移20枚DAI到NEAR](https://learnnear.club/near-ethereum/)上。当然不可能在两个网络之间物理的转移通证，这意味着我们需要将20枚DAI移出以太坊上的流通，再投放20枚DAI到NEAR上流通，这样总的DAI流通量保持不变。
建議 "当然不可能在两个网络之间物理的转移通证" 轉為 "当然不可能在两个网络之间將通证進行物理转移"

2021-07-03 04:13 UTC, wongxf reviewed
```suggestion
假设我要从 [以太坊转移20枚DAI到NEAR](https://learnnear.club/near-ethereum/)上。 由于通证不可能在网络之间进行物理转移，这意味着我们需要将 20 个 DAI 从以太坊上的流通中取出，并在 NEAR 上将 20 个 DAI 放入流通中，这样DAI总 的供应量就不会发生变化。
···

2021-07-03 05:34 UTC, MartinYeung5 requested changes

2021-07-03 05:34 UTC, MartinYeung5 commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +7. NEAR上的**ERC-20 连接器**接下来查找NEAR上**轻节点**的以太坊区块头，独立计算出密码学证明。
NEAR上的**ERC-20 连接器**接下来查找NEAR上**轻节点**的以太坊区块头，然后创建一个独立计算出来的密码学证明。

2021-07-04 01:54 UTC, shepf commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +4. 然而空口无凭，NEAR要求我提供20枚DAI已经在以太坊上锁定的证明；
@wangxf 你把人家的序号4 都给弄丢了

2021-07-12 04:24 UTC, marco-sundsk commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +**中继(Relayer)** — 轻节点是智能合约，它们不会自己运行和更新信息。中继是一些脚本，运行于传统服务器上，它们周期性地从一个区块链上读取块，传递给运行于另一个链上的轻节点。也就是说，中继保持轻节点的数据最新。
中继更常用一些

2021-07-12 04:25 UTC, marco-sundsk commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +4. 接下来我要请求NEAR网络基于刚才以太坊上活动而创建一些DAI，就先要等待**中继**发送大概20个以太坊区块头给运行在NEAR上的**轻节点**。这是为了安全的考虑，跟你充值给虚拟币交易所时需要等一些确认一样。
中继更常用

2021-07-12 04:31 UTC, marco-sundsk commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +NEAR协议构建了[彩虹桥](https://ethereum.bridgetonear.org/)—一个在密码学领域独特且高价值的全去中心化桥，可以在以太坊与NEAR之间，以及最终与极光(Aurora)之间转移通证。已有一些技术文档描述这个桥，而本文希望能让任何一个对密码学有基本认识的人能了解这个桥的工作机制。
已修改

2021-07-12 04:33 UTC, marco-sundsk commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +假设我要从[以太坊转移20枚DAI到NEAR](https://learnnear.club/near-ethereum/)上。当然不可能在两个网络之间物理的转移通证，这意味着我们需要将20枚DAI移出以太坊上的流通，再投放20枚DAI到NEAR上流通，这样总的DAI流通量保持不变。
已修改

2021-07-12 04:33 UTC, marco-sundsk commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +7. NEAR上的**ERC-20 连接器**接下来查找NEAR上**轻节点**的以太坊区块头，独立计算出密码学证明。
已修改

2021-07-29 03:30 UTC, think-in-universe requested changes

2021-07-29 03:30 UTC, think-in-universe commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +2. 当我在[MetaMask](https://metamask.io/)上确认了两笔交易中的第一笔，彩虹桥与以太坊上的**ERC-20 连接器**通信 (因为DAI是一个ERC-20通证)，连接器将这20枚DAI锁定在它的保管库中。至此，这笔DAI就不再在以太坊上流通了。
`两笔交易中的第一笔` (first of two transactions) 原文表达可能稍微有些问题，这里应该是指前两笔交易（approve 和 transfer）

![image](https://user-images.githubusercontent.com/46699230/127426993-890f3180-0f15-4833-a777-04c61400b608.png)

2021-07-29 03:30 UTC, think-in-universe commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +要深度了解彩虹桥，你可以[阅读该文档](https://near.org/blog/eth-near-rainbow-bridge/),。要跟进极光的所有相关信息，轻[关注极光的推特！](https://twitter.com/auroraisnear)
```suggestion
要深度了解彩虹桥，你可以[阅读该文档](https://near.org/blog/eth-near-rainbow-bridge/)。要跟进极光的所有相关信息，请[关注极光的推特！](https://twitter.com/auroraisnear)
```

2021-07-29 04:23 UTC, marco-sundsk commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +2. 当我在[MetaMask](https://metamask.io/)上确认了两笔交易中的第一笔，彩虹桥与以太坊上的**ERC-20 连接器**通信 (因为DAI是一个ERC-20通证)，连接器将这20枚DAI锁定在它的保管库中。至此，这笔DAI就不再在以太坊上流通了。
确实，我们就采纳前"两笔交易"并加括号注释的方式

2021-07-29 04:24 UTC, marco-sundsk commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +2. 当我在[MetaMask](https://metamask.io/)上确认了两笔交易中的第一笔，彩虹桥与以太坊上的**ERC-20 连接器**通信 (因为DAI是一个ERC-20通证)，连接器将这20枚DAI锁定在它的保管库中。至此，这笔DAI就不再在以太坊上流通了。
```suggestion
2. 当我在[MetaMask](https://metamask.io/)上确认了前两笔交易(approve 和 transfer)，彩虹桥与以太坊上的**ERC-20 连接器**通信 (因为DAI是一个ERC-20通证)，连接器将这20枚DAI锁定在它的保管库中。至此，这笔DAI就不再在以太坊上流通了。
```

2021-07-29 04:29 UTC, think-in-universe approved these changes

2021-07-29 04:29 UTC, merged

2021-08-14 03:46 UTC, MartinYeung5 commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +要深度了解彩虹桥，你可以[阅读该文档](https://near.org/blog/eth-near-rainbow-bridge/)。要跟进极光的所有相关信息，请[关注极光的推特！](https://twitter.com/auroraisnear)
要深度了解彩虹桥，你可以[阅读该文档](https://near.org/blog/eth-near-rainbow-bridge/)。要跟进极光的所有相关信息，请[关注极光的推特！](https://twitter.com/auroraisnear)

原文链接：https://learnnear.club/how-the-near-rainbow-bridge-works/

2021-08-14 03:48 UTC, MartinYeung5 commented on cn/resources/guides/how-the-near-rainbow-bridge-works.md
> +当我要把DAI转移回以太坊，流程反转。不过我们不是在NEAR上锁定那20枚DAI，而是销毁它，也叫做燃烧。然后我们提供燃烧的证明给运行于以太坊上的连接器。通过访问运行于以太坊上的轻节点里的NEAR区块数据，连接器验证那个证明，随后从保管库里释放20枚DAI并发送给我我的钱包!
当我要把DAI转移回以太坊，流程反转。不过我们不是在NEAR上锁定那20枚DAI，而是销毁它，也叫做燃烧。然后我们提供燃烧的证明给运行于以太坊上的连接器。通过访问运行于以太坊上的轻节点里的NEAR区块数据，连接器验证那个证明，随后从保管库里释放20枚DAI并发送给我的钱包!

2021-08-17 02:03 UTC, wongxf commented
翻译质量评价: 优秀

2021-08-18 14:37 UTC, MartinYeung5 commented
翻译质量评价: 优秀

2021-08-19 03:48 UTC, think-in-universe commented
翻译质量评价: 优秀